#!/usr/bin/env python3
"""Add jobs from company career pages — 20 Sep 2026."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "import_park_jobs", ROOT / "scripts" / "import-park-jobs-latest.py"
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

NOTE = mod.NOTE
POSTED = "2026-09-20"
SRC = "Company careers page"


def job(**kwargs) -> dict:
    base = {
        "logo": "",
        "postedDate": POSTED,
        "source": SRC,
        "verified": True,
        "verificationNote": NOTE,
        "isWalkIn": False,
        "walkInDate": "",
        "startingDate": "",
        "skills": [],
        "applyDeadline": "Rolling",
        "benefits": [
            "Listing transcribed from the employer's official careers page",
            "Never pay anyone for this application",
        ],
    }
    base.update(kwargs)
    return base


JOBS = [
    job(
        id="accenture-associate-engineer-frontend-kochi-sep2026",
        company="Accenture",
        companyBlurb="Accenture · Associate Engineer – FrontEnd · Kochi · R00357359",
        location="Kochi, Kerala",
        roles=["Associate Engineer – FrontEnd Development"],
        experience="experienced",
        experienceRange="1–2 years",
        employmentType="Full-time",
        tags=["IT", "Frontend"],
        email="",
        phone="",
        website="https://www.accenture.com/in-en/careers",
        applyLink="https://www.accenture.com/in-en/careers/jobdetails?id=R00357359_en",
        industry="IT / Consulting",
        companyDetails="Accenture ACS Song is hiring an Associate Engineer for frontend development in Kochi.",
        workDetails="1–2 years building user-facing web applications. React, Next.js, and foundational Node.js. Strong HTML, CSS, and JavaScript fundamentals required.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="1–2 years",
        skills=["HTML", "CSS", "JavaScript", "React", "Next.js", "Node.js", "Jest", "Git"],
        requirements=[
            "Graduation required",
            "1–2 years hands-on frontend development experience",
            "Strong JavaScript fundamentals including promises and async programming",
            "Hands-on React experience with hooks and component lifecycle",
            "Working knowledge of Next.js routing and rendering basics",
            "Foundational Node.js backend exposure under guidance",
        ],
        responsibilities=[
            "Develop and maintain frontend features using React and Next.js",
            "Translate UI designs and Figma specs into responsive interfaces",
            "Integrate frontend components with backend APIs",
            "Write unit tests and participate in code reviews and agile ceremonies",
        ],
        howToApply="Apply on Accenture careers: https://www.accenture.com/in-en/careers/jobdetails?id=R00357359_en",
        hiringNotes="Source: Accenture careers · Job R00357359 · Sep 2026.",
        description="Associate Engineer – FrontEnd at Accenture · Kochi · 1–2 yrs · React/Next.js/Node.js.",
    ),
    job(
        id="aabasoft-flutter-development-internship-kochi-sep2026",
        company="Aabasoft",
        companyBlurb="Aabasoft · Internship – Flutter Development · Kochi",
        location="Kochi, Kerala",
        roles=["Flutter Development Intern"],
        experience="fresher",
        experienceRange="Internship · 6 months",
        employmentType="Internship",
        tags=["IT", "Mobile", "Internship"],
        email="jobs@aabasoft.in",
        phone="+91 9249151111",
        website="https://www.aabasoft.com",
        applyLink="https://www.aabasoft.com/in-en/carrerdetails/internship---flutter-development/",
        address="Aabasoft, Chakolas Heights, Seaport-Airport Road, Kochi; Vismaya, Infopark",
        industry="IT / Software",
        companyDetails="Aabasoft Technologies India Private Limited offers a Flutter development internship with mentorship and certificate on completion.",
        workDetails="6-month internship building cross-platform mobile apps with Flutter and Dart. Chance to convert to full-time based on performance.",
        workStatus="Internship",
        workMode="On-site · Kochi",
        experienceYears="Student / Fresher",
        skills=["Flutter", "Dart", "REST APIs", "Git", "Provider", "Bloc", "Riverpod"],
        requirements=[
            "Pursuing or recently completed CS, IT, or related degree",
            "Basic understanding of REST APIs and Git",
            "Portfolio of Flutter projects is a plus",
            "Familiarity with Provider, Bloc, or Riverpod preferred",
        ],
        responsibilities=[
            "Assist in designing and developing cross-platform mobile apps using Flutter",
            "Collaborate with UI/UX, backend, and product teams",
            "Debug issues and participate in code reviews",
        ],
        howToApply="Apply via https://www.aabasoft.com/in-en/carrerdetails/internship---flutter-development/ or email jobs@aabasoft.in",
        hiringNotes="Source: Aabasoft careers · Sep 2026.",
        description="Flutter Development Internship at Aabasoft · Kochi · 6 months.",
    ),
    job(
        id="brahmaa-wordpress-developer-kochi-sep2026",
        company="Brahmaa Infotek",
        companyBlurb="Brahmaa Infotek · WordPress Developer · Kakkanad, Kochi",
        location="Kakkanad, Kochi",
        roles=["WordPress Developer"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["IT", "Web Development"],
        email="support@brahmaait.com",
        phone="+91 9446355222",
        website="https://www.brahmaait.com",
        applyLink="https://www.brahmaait.com/career/",
        address="1st Floor, Plot No. 193, Mavelipuram, Kakkanad, Kochi",
        industry="IT / Web Development",
        companyDetails="Brahmaa Infotek is hiring a WordPress Developer in Ernakulam/Kochi.",
        workDetails="Develop and maintain WordPress websites. Customize themes and plugins. Work on live client projects.",
        workStatus="Full-time",
        workMode="On-site · Kakkanad",
        experienceYears="As per hiring notice",
        skills=["WordPress", "PHP", "HTML", "CSS", "JavaScript"],
        requirements=[
            "Strong WordPress development skills",
            "Passion for technology and willingness to learn in a team environment",
        ],
        responsibilities=[
            "Develop and maintain WordPress websites",
            "Customize themes and plugins for client projects",
            "Collaborate with designers and developers on delivery",
        ],
        howToApply="Email support@brahmaait.com or apply via https://www.brahmaait.com/career/",
        hiringNotes="Source: Brahmaa Infotek careers · Sep 2026.",
        description="WordPress Developer at Brahmaa Infotek · Kakkanad, Kochi.",
    ),
    job(
        id="brahmanet-careers-kochi-sep2026",
        company="Brahmanet IT Solutions",
        companyBlurb="Brahmanet · Multiple IT roles · Kakkanad, Kochi",
        location="Kakkanad, Kochi",
        roles=[
            "WordPress Developer",
            "SEO & Digital Marketing Executive",
            "Junior Software Developer",
            "Developer cum Server Administrator",
            "Team Lead – Full Stack & AI",
            "Software Engineer – Full Stack & AI",
            "Junior Developer",
            "PHP Developer",
            "Software Developer",
            "Android Developer",
            "iOS Developer",
        ],
        experience="both",
        experienceRange="Fresher to 3+ years (role-specific)",
        employmentType="Full-time",
        tags=["IT", "Web Development", "Mobile"],
        email="hr@brahmanet.com",
        phone="+91 484 2973997",
        website="https://brahmanet.com",
        applyLink="https://brahmanet.com/career/",
        address="27/1001, Plot No. 193, Mavelipuram, Kakkanad, Kochi 682030",
        industry="IT / Software / Digital Marketing",
        companyDetails="Brahmanet IT Solutions is hiring across web, mobile, SEO, and full-stack roles in Kakkanad.",
        workDetails="Openings include WordPress (1+ yr), SEO & Digital Marketing (1+ yr), Junior/Full Stack developers (1+ yr), PHP (3+ yrs), Android/iOS (1+ yr), and Team Lead Full Stack & AI (3+ yrs). AI/LLM integration experience is an advantage for developer roles.",
        workStatus="Full-time",
        workMode="On-site · Kakkanad",
        experienceYears="Role-specific",
        skills=["WordPress", "PHP", "Python", "Flutter", "React Native", "Android", "iOS", "SEO", "Linux"],
        requirements=[
            "Relevant qualification: B.Tech CS/IT, MCA, or equivalent",
            "Experience as per the role applied",
            "Mention designation in email subject when applying",
        ],
        responsibilities=[
            "Deliver web, mobile, or marketing projects as per assigned role",
            "Collaborate in a team culture with live project exposure",
        ],
        howToApply="Email hr@brahmanet.com with the designation in the subject line",
        hiringNotes="Source: Brahmanet careers page · Sep 2026.",
        description="Multiple IT openings at Brahmanet · Kakkanad · Web, mobile, SEO, full-stack.",
    ),
    job(
        id="nest-digital-careers-sep2026",
        company="NeST Digital",
        companyBlurb="NeST Digital · Careers portal · Kochi / Technopark",
        location="Kochi / Thiruvananthapuram, Kerala",
        roles=["Multiple openings"],
        experience="both",
        experienceRange="Role-specific",
        employmentType="Full-time",
        tags=["IT"],
        email="",
        phone="",
        website="https://nestdigital.com",
        applyLink="https://careers.nestdigital.com/",
        industry="IT / Digital Engineering",
        companyDetails="NeST Digital publishes current openings on its dedicated careers portal.",
        workDetails="Browse and apply for software engineering and related roles on the official NeST Digital careers site.",
        workStatus="Full-time",
        workMode="As per role",
        experienceYears="Role-specific",
        skills=["Software engineering"],
        requirements=["Check individual role requirements on the careers portal"],
        responsibilities=["As per the role applied on careers.nestdigital.com"],
        howToApply="Browse and apply at https://careers.nestdigital.com/",
        hiringNotes="Source: NeST Digital careers portal · Sep 2026. Roles load dynamically on the site.",
        description="NeST Digital careers · Apply via careers.nestdigital.com.",
    ),
    job(
        id="eyet-innovations-careers-edappally-sep2026",
        company="EyeT Innovations",
        companyBlurb="EyeT Innovations · 7 openings · Edappally, Kochi",
        location="Edappally, Kochi",
        roles=[
            "PHP/Laravel Developer",
            "UI/UX Designer",
            "Flutter Developer",
            "Python Developer",
            "Offshore Business Development Manager",
            "HR Admin",
            "Chief Marketing Officer",
        ],
        experience="both",
        experienceRange="Role-specific",
        employmentType="Full-time",
        tags=["IT", "Design", "HR", "Marketing"],
        email="info@eyetinnovations.com",
        phone="+91 8547553629",
        website="https://eyetinnovations.com",
        applyLink="https://eyetinnovations.com/careers",
        address="37/28/9-B, Ground Floor, Sivasailam Complex, Changampuzha Samadhi Road, Edappally 682024",
        industry="IT / Software",
        companyDetails="EyeT Innovations Software Solutions is hiring across development, design, HR, and business development in Edappally.",
        workDetails="Open roles span PHP/Laravel, UI/UX, Flutter, Python, offshore BD, HR admin, and CMO. Apply via the careers page.",
        workStatus="Full-time",
        workMode="On-site · Edappally",
        experienceYears="Role-specific",
        skills=["Laravel", "Flutter", "Python", "UI/UX", "Business development"],
        requirements=["Relevant experience for the role applied"],
        responsibilities=["Develop, design, or support business operations as per role"],
        howToApply="Apply via https://eyetinnovations.com/careers or email info@eyetinnovations.com",
        hiringNotes="Source: EyeT Innovations careers · Sep 2026.",
        description="7 openings at EyeT Innovations · Edappally · Dev, design, HR, BD.",
    ),
    job(
        id="citrus-informatics-careers-kochi-sep2026",
        company="Citrus Informatics",
        companyBlurb="Citrus Informatics · 13+ engineering roles · Kochi",
        location="Kochi, Kerala",
        roles=[
            "Software Engineer – Python/Django/MySQL",
            "Software Engineer – RPA/Blue Prism",
            "Senior Business Analyst",
            "Digital Marketing & Content Analyst",
            "System/Network/Security Engineer",
            "Software Quality Engineer",
            "Software Engineer – Database and SQL",
            "Software Engineer – Angular/React.JS",
            "Software Engineer – Android/iOS/Hybrid",
            "Software Engineer – Java/JEE",
            "Software Engineer – ASP.NET/C#/SQL Server",
            "Software Engineer – WordPress/Drupal/PHP/MySQL",
            "Technology Project Manager / Senior Project Lead",
        ],
        experience="experienced",
        experienceRange="2–15 years (role-specific)",
        employmentType="Full-time",
        tags=["IT"],
        email="info@citrusinformatics.com",
        phone="+91 484 2575517",
        website="https://www.citrusinformatics.com",
        applyLink="https://www.citrusinformatics.com/opportunities/",
        industry="IT / Software Services",
        companyDetails="Citrus Informatics is expanding its Kochi team across engineering, QA, BA, DevOps, and project management.",
        workDetails="B.Tech/MSc/MCA/M.Tech in Computer Science with 2–15 years relevant experience depending on role. Full-time positions in Kochi.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="2–15 years",
        skills=["Python", "Java", ".NET", "React", "Angular", "Mobile", "QA", "DevOps"],
        requirements=[
            "B.Tech/MSc/MCA/M.Tech in Computer Science or related field",
            "2–15 years in medium to large-scale software development (role-specific)",
        ],
        responsibilities=[
            "Deliver software, QA, BA, or infrastructure work as per assigned role",
        ],
        howToApply="Email info@citrusinformatics.com or see https://www.citrusinformatics.com/opportunities/",
        hiringNotes="Source: Citrus Informatics opportunities page · Sep 2026.",
        description="13+ IT roles at Citrus Informatics · Kochi · Python, Java, .NET, mobile, QA.",
    ),
    job(
        id="efftabs-careers-kochi-sep2026",
        company="EFFTABS Solutions LLP",
        companyBlurb="EFFTABS · Mobile, .NET, Sales roles · Kochi",
        location="Kochi, Kerala",
        roles=[
            "Mobile Application Developer",
            "Senior Software Developer",
            "Business Development / Marketing Executive",
            "Tele Marketing Executive",
        ],
        experience="both",
        experienceRange="Fresher to 5 years (role-specific)",
        employmentType="Full-time",
        tags=["IT", "Sales"],
        email="",
        phone="04844054243",
        website="https://efftabs.com",
        applyLink="https://efftabs.com/about-us/careers/",
        industry="IT / Software",
        companyDetails="EFFTABS Solutions LLP is hiring mobile developers, senior .NET developers, and sales/marketing staff in Kochi.",
        workDetails="Mobile dev (2+ yrs, Flutter/Firebase, 5 openings); Senior Software Developer (3–5 yrs, C#/ASP.NET Core, 12 openings); BD/Marketing Executive (MBA/PGDM 1–3 yrs, 10 openings); Tele Marketing (English & Hindi, 2 openings).",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="Role-specific",
        skills=["Flutter", "ASP.NET Core", "PostgreSQL", "Sales", "Telemarketing"],
        requirements=[
            "Mobile: 2+ years Android/Flutter, published app preferred",
            "Senior dev: 3–5 years C#/ASP.NET Core",
            "BD: MBA/PGDM 1–3 years in software/technology services",
            "Tele marketing: Fluent English and Hindi",
        ],
        responsibilities=[
            "Build mobile or .NET solutions, or drive sales as per role",
        ],
        howToApply="Apply via https://efftabs.com/about-us/careers/ or call 0484 405 4243",
        hiringNotes="Source: EFFTABS careers page · Sep 2026.",
        description="EFFTABS hiring · Kochi · Flutter mobile, .NET senior dev, BD, tele marketing.",
    ),
    job(
        id="equifax-kerala-careers-trivandrum-sep2026",
        company="Equifax",
        companyBlurb="Equifax · 13 technology roles · Trivandrum / Kerala",
        location="Trivandrum, Kerala",
        roles=[
            "Senior Software Engineer",
            "Data Engineer",
            "Data Scientist",
            "Lead Software Engineer",
            "P3 Lead Software Engineer",
            "Software Engineer",
            "Technical Product Owner",
            "Software Engineer – Front Line Manager",
            "Technical Solutions Architect – Specialist",
            "Lead Software Engineer – Specialist",
            "Principal Engineer – Agentic Engineering",
        ],
        experience="experienced",
        experienceRange="Career-level (role-specific)",
        employmentType="Full-time",
        tags=["IT", "Data"],
        email="",
        phone="",
        website="https://www.equifax.com",
        applyLink="https://careers.equifax.com/en/jobs/?search=&country=India&region=Kerala&pagesize=20",
        industry="BFSI / Data & Analytics",
        companyDetails="Equifax is hiring technology and data professionals in Trivandrum, Kerala.",
        workDetails="Current Kerala openings include software engineering, data engineering, data science, technical product ownership, and architecture roles. Some roles also list Pune.",
        workStatus="Full-time",
        workMode="On-site · Trivandrum",
        experienceYears="Role-specific",
        skills=["Software engineering", "Data engineering", "Data science", "Product management"],
        requirements=["Check individual job requirements on Equifax careers portal"],
        responsibilities=["Deliver technology and data solutions as per assigned role"],
        howToApply="Apply via https://careers.equifax.com/en/jobs/?country=India&region=Kerala",
        hiringNotes="Source: Equifax careers · Kerala filter · Sep 2026.",
        description="Equifax Kerala/Trivandrum tech hiring · Software, data, product, architecture.",
    ),
    job(
        id="egc-global-services-careers-infopark-sep2026",
        company="EGC Global Services India Pvt Ltd",
        companyBlurb="EGC Global Services · Infopark Phase 1 · Multiple roles",
        location="Infopark Phase 1, Kakkanad, Kochi",
        roles=[
            "Associate – Catalog",
            "Junior Software Engineer – .NET",
            "Junior Software Engineer – Frontend",
            "Project Manager",
            "Senior Manager / Head – Product Data, Catalog & eCommerce Operations",
            "Senior Software Engineer – .NET",
        ],
        experience="both",
        experienceRange="Role-specific",
        employmentType="Full-time",
        tags=["IT", "Infopark"],
        email="egcgshr@theegc.com",
        phone="",
        website="https://egcgs.theegc.com",
        applyLink="https://egcgs.theegc.com/careers/",
        address="2nd Floor, THAPASYA, Infopark Phase 1, Kakkanad, Kochi 682042",
        industry="IT / BPO / eCommerce",
        companyDetails="EGC Global Services India Pvt Ltd is hiring at Infopark Phase 1, Kakkanad.",
        workDetails="Openings across catalog operations, .NET and frontend engineering, project management, and product data leadership.",
        workStatus="Full-time",
        workMode="On-site · Infopark Phase 1",
        experienceYears="Role-specific",
        skills=[".NET", "Frontend", "Catalog", "eCommerce", "Project management"],
        requirements=["Relevant experience for the role applied"],
        responsibilities=["Support catalog, engineering, or PM functions as per role"],
        howToApply="Email egcgshr@theegc.com or apply via https://egcgs.theegc.com/careers/",
        hiringNotes="Source: EGC Global Services careers · Sep 2026.",
        description="EGC Global Services hiring · Infopark Phase 1 · .NET, frontend, catalog, PM.",
    ),
    job(
        id="vidyalai-full-stack-developer-kochi-sep2026",
        company="Vidyalai",
        companyBlurb="Vidyalai · Full Stack Developer · Kochi · Ed-Tech",
        location="Kochi, Kerala",
        roles=["Full Stack Developer"],
        experience="both",
        experienceRange="Hands-on experience required",
        employmentType="Full-time",
        tags=["IT", "Ed Tech"],
        email="",
        phone="",
        website="https://vidyalai.com",
        applyLink="https://erp.vidyalai.com/jobs/vidyalai/full-stack-developer",
        industry="Ed Tech",
        companyDetails="Vidyalai is an Ed-Tech startup founded by IIT Madras alumni, building personalised online learning for students in 30+ countries.",
        workDetails="Full-time developer role building the online learning platform with React, Node.js, Express, WebSockets, and MongoDB.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="Hands-on experience",
        skills=["React", "Next.js", "Redux", "Node.js", "Express", "Socket.io", "MongoDB", "REST APIs"],
        requirements=[
            "Hands-on experience in at least a few of the listed technologies",
            "Passion demonstrated through side projects, internships, or past work",
            "Do not apply if you do not meet the above criteria (per employer notice)",
        ],
        responsibilities=[
            "Write clean, maintainable code with React frontend and Node/Express/MongoDB backend",
            "Design, build, test, and deploy production-ready features",
            "Develop scalable REST API endpoints",
        ],
        howToApply="Apply at https://erp.vidyalai.com/jobs/vidyalai/full-stack-developer",
        hiringNotes="Source: Vidyalai careers · Sep 2026.",
        description="Full Stack Developer at Vidyalai · Kochi · React/Node/MongoDB · Ed-Tech.",
    ),
    job(
        id="emsyne-careers-portal-sep2026",
        company="Emsyne Technologies",
        companyBlurb="Emsyne Technologies · Careers · Infopark, Kochi",
        location="Infopark, Kochi",
        roles=["Multiple openings"],
        experience="both",
        experienceRange="Role-specific",
        employmentType="Full-time",
        tags=["IT", "Infopark"],
        email="",
        phone="",
        website="https://www.emsyne.com",
        applyLink="https://www.emsyne.com/careers.html",
        industry="IT / Software",
        companyDetails="Emsyne Technologies Private Limited publishes openings on its careers page and the Infopark jobs portal.",
        workDetails="Check Emsyne's official careers page and Infopark portal for current engineering and support roles.",
        workStatus="Full-time",
        workMode="On-site · Infopark",
        experienceYears="Role-specific",
        skills=["Software engineering"],
        requirements=["See official Emsyne careers page for current openings"],
        responsibilities=["As per role on official careers channel"],
        howToApply="See https://www.emsyne.com/careers.html and Infopark jobs portal",
        hiringNotes="Source: Emsyne careers page · Sep 2026. Additional roles may also appear on infopark.in.",
        description="Emsyne Technologies careers · Infopark · Check official page for openings.",
    ),
]


def main() -> None:
    n = mod.insert_jobs(ROOT / "data" / "jobs-data.js", "JOBS", JOBS)
    print(f"Added {n} company careers jobs to jobs-data.js")


if __name__ == "__main__":
    main()
