#!/usr/bin/env python3
"""Add WhatsApp hiring creatives collected 20 Sep 2026."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "import_park_jobs", ROOT / "scripts" / "import-park-jobs-latest.py"
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

NOTE = mod.NOTE
POSTED = "2026-09-20"


def job(**kwargs) -> dict:
    base = {
        "logo": "",
        "postedDate": POSTED,
        "source": "WhatsApp",
        "verified": True,
        "verificationNote": NOTE,
        "isWalkIn": False,
        "walkInDate": "",
        "startingDate": "",
        "skills": [],
        "applyDeadline": "Rolling",
        "benefits": [
            "Listing transcribed from an employer hiring creative",
            "Never pay anyone for this application",
        ],
    }
    base.update(kwargs)
    return base


JOBS = [
    job(
        id="mosons-group-sales-executive-palakkad-sep2026",
        company="Mosons Group",
        companyBlurb="Mosons Group · Sales Executive · Palakkad & Kerala",
        location="Palakkad, Kerala",
        roles=["Sales Executive"],
        experience="fresher",
        experienceRange="Freshers welcome · Age up to 35",
        employmentType="Full-time",
        tags=["Sales", "FMCG"],
        email="",
        phone="+91 95266 06750",
        website="",
        industry="FMCG / Retail",
        companyDetails="Mosons Group represents brands including Indulekha, Beevi's, Happenstance, and Malayalima across Kerala.",
        workDetails="Sales Executive role with CTC around ₹27,050 per month. Freshers welcome. Candidates up to 35 years may apply.",
        workStatus="Full-time",
        workMode="Field sales across Kerala",
        experienceYears="Freshers welcome",
        skills=["Sales", "Field marketing", "FMCG"],
        requirements=[
            "Freshers welcome",
            "Age up to 35 years",
            "Willingness to work in field sales across Kerala",
        ],
        responsibilities=[
            "Drive sales for Mosons Group brands",
            "Build retailer and distributor relationships",
            "Achieve monthly sales targets",
        ],
        howToApply="Call +91 95266 06750",
        hiringNotes="Source: Mosons Group hiring creative · Sep 2026.",
        description="Sales Executive at Mosons Group · Palakkad · Freshers welcome · ~₹27,050 CTC/month.",
    ),
    job(
        id="whiteband-ai-business-data-analyst-kochi-sep2026",
        company="Whiteband AI",
        companyBlurb="Whiteband AI · Business & Data Analyst · Panampilly Nagar, Kochi",
        location="Panampilly Nagar, Kochi",
        roles=["Business & Data Analyst"],
        experience="experienced",
        experienceRange="3–5 years",
        employmentType="Full-time",
        tags=["Data", "Analytics", "IT"],
        email="lazim@mylaw.net",
        phone="",
        website="",
        industry="Technology / AI",
        companyDetails="Whiteband AI is hiring a Business & Data Analyst for its Kochi office.",
        workDetails="3–5 years experience. Python and SQL required. ₹7–9 LPA. Work from office at Panampilly Nagar, Kochi.",
        workStatus="Full-time",
        workMode="On-site · Panampilly Nagar",
        experienceYears="3–5 years",
        skills=["Python", "SQL", "Data analysis", "Business analysis"],
        requirements=[
            "3–5 years of relevant experience",
            "Strong Python and SQL skills",
            "Ability to work from office at Panampilly Nagar, Kochi",
        ],
        responsibilities=[
            "Analyse business and product data",
            "Build reports and dashboards",
            "Support data-driven decision making",
        ],
        howToApply="Email lazim@mylaw.net with your CV",
        hiringNotes="Source: Whiteband AI hiring creative · Sep 2026.",
        description="Business & Data Analyst at Whiteband AI · 3–5 yrs · Python/SQL · ₹7–9 LPA · Kochi.",
    ),
    job(
        id="zeed-academy-faculty-thodupuzha-sep2026",
        company="Zeed Academy",
        companyBlurb="Zeed Academy · Interior / Graphic / Logistics Faculty · Thodupuzha",
        location="Thodupuzha, Kerala",
        roles=[
            "Interior Design Faculty",
            "Graphic Design Faculty",
            "Logistics Faculty",
        ],
        experience="both",
        experienceRange="As per academy requirements",
        employmentType="Full-time",
        tags=["Education", "Faculty"],
        email="",
        phone="+91 8592 955 855",
        website="",
        industry="Education / Training",
        companyDetails="Zeed Academy is hiring faculty for interior design, graphic design, and logistics programmes in Thodupuzha.",
        workDetails="Faculty openings across interior design, graphic design, and logistics. Based at Thodupuzha.",
        workStatus="Full-time",
        workMode="On-site · Thodupuzha",
        experienceYears="As per academy requirements",
        skills=["Teaching", "Subject expertise", "Curriculum delivery"],
        requirements=[
            "Relevant qualification and teaching experience in the subject area",
            "Good communication skills",
            "Willingness to work at Thodupuzha campus",
        ],
        responsibilities=[
            "Deliver classroom and practical training",
            "Prepare lesson plans and assessments",
            "Guide students on projects and placements",
        ],
        howToApply="Call +91 8592 955 855",
        hiringNotes="Source: Zeed Academy hiring creative · Sep 2026.",
        description="Faculty openings at Zeed Academy · Interior / Graphic / Logistics · Thodupuzha.",
    ),
    job(
        id="canapprove-education-head-thrissur-sep2026",
        company="CanApprove",
        companyBlurb="CanApprove · Education Head · Thrissur",
        location="Thrissur, Kerala",
        roles=["Education Head"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Education", "Immigration"],
        email="devikr@canapprove.com",
        phone="+91 79947 99908",
        website="",
        industry="Education / Immigration consultancy",
        companyDetails="CanApprove is an immigration and education consultancy hiring an Education Head for Thrissur.",
        workDetails="Lead education counselling and programme guidance. Based at Thrissur.",
        workStatus="Full-time",
        workMode="On-site · Thrissur",
        experienceYears="As per hiring notice",
        skills=["Education counselling", "Team leadership", "Study abroad programmes"],
        requirements=[
            "Experience in education counselling or study-abroad advisory",
            "Strong leadership and communication skills",
        ],
        responsibilities=[
            "Lead education counselling operations",
            "Guide counsellors on programmes and admissions",
            "Drive student enrolment and service quality",
        ],
        howToApply="Email devikr@canapprove.com or call +91 79947 99908",
        hiringNotes="Source: CanApprove hiring creative · Sep 2026.",
        description="Education Head at CanApprove · Thrissur.",
    ),
    job(
        id="canapprove-immigration-consultant-kerala-sep2026",
        company="CanApprove",
        companyBlurb="CanApprove · Immigration Consultant · Thrissur, Thiruvalla, Angamaly, Kochi, Kozhikode",
        location="Thrissur, Thiruvalla, Angamaly, Kochi, Kozhikode",
        roles=["Immigration Consultant"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Immigration", "Sales", "Consulting"],
        email="hrrecruiter.canapprove@gmail.com",
        phone="+91 79944 99915",
        website="",
        industry="Immigration consultancy",
        companyDetails="CanApprove is hiring immigration consultants across multiple Kerala branches.",
        workDetails="Immigration consultant roles at Thrissur, Thiruvalla, Angamaly, Kochi, and Kozhikode.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="As per hiring notice",
        skills=["Immigration counselling", "Sales", "Client management"],
        requirements=[
            "Experience in immigration consultancy preferred",
            "Strong communication and counselling skills",
        ],
        responsibilities=[
            "Counsel clients on immigration programmes",
            "Convert leads and manage applications",
            "Maintain knowledge of destination-country requirements",
        ],
        howToApply="Email hrrecruiter.canapprove@gmail.com or call +91 79944 99915",
        hiringNotes="Source: CanApprove hiring creative · Sep 2026.",
        description="Immigration Consultant at CanApprove · Multiple Kerala locations.",
    ),
    job(
        id="canapprove-branch-manager-kochi-sep2026",
        company="CanApprove",
        companyBlurb="CanApprove · Branch Manager (Immigration Sales) · Kochi",
        location="Kochi, Kerala",
        roles=["Branch Manager (Immigration Sales)"],
        experience="experienced",
        experienceRange="4–5 years",
        employmentType="Full-time",
        tags=["Immigration", "Sales", "Management"],
        email="hrrecruiter.canapprove@gmail.com",
        phone="+91 79944 99915",
        website="",
        industry="Immigration consultancy",
        companyDetails="CanApprove is hiring a Branch Manager for immigration sales at Kochi.",
        workDetails="4–5 years experience as Branch Manager or Assistant Branch Manager in immigration consultancy. Age below 35. Female candidates preferred.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="4–5 years",
        skills=["Branch management", "Sales leadership", "Immigration programmes"],
        requirements=[
            "4–5 years experience as Branch Manager or Assistant Branch Manager in immigration consultancy",
            "Proven leadership and sales management experience",
            "Age below 35",
            "Female candidates preferred",
        ],
        responsibilities=[
            "Manage branch operations and achieve sales targets",
            "Drive revenue growth and monitor branch performance",
            "Handle lead conversion and sales reporting",
            "Maintain knowledge of Canada, Australia, UK, and other immigration programmes",
        ],
        howToApply="Email hrrecruiter.canapprove@gmail.com or call +91 79944 99915",
        hiringNotes="Source: CanApprove hiring creative · Sep 2026.",
        description="Branch Manager (Immigration Sales) at CanApprove · Kochi · 4–5 yrs.",
    ),
    job(
        id="melden-junior-senior-accountants-kochi-sep2026",
        company="MelDen Advisory",
        companyBlurb="MelDen · Junior & Senior Accountants · Kochi",
        location="Kochi, Kerala",
        roles=["Junior Accountant", "Senior Accountant"],
        experience="experienced",
        experienceRange="2+ years",
        employmentType="Full-time",
        tags=["Accounts", "Finance"],
        email="Riya@meldenadvisory.com",
        phone="",
        website="",
        industry="Accounting / Advisory",
        companyDetails="MelDen Advisory is hiring junior and senior accountants in Kochi.",
        workDetails="2+ years experience. B.Com or M.Com. GST and UAE VAT knowledge preferred.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="2+ years",
        skills=["Accounting", "GST", "UAE VAT", "Tally"],
        requirements=[
            "B.Com or M.Com",
            "Minimum 2 years of accounting experience",
            "GST knowledge required; UAE VAT exposure preferred",
        ],
        responsibilities=[
            "Handle day-to-day accounting and bookkeeping",
            "Prepare GST returns and compliance filings",
            "Support financial reporting and reconciliations",
        ],
        howToApply="Email Riya@meldenadvisory.com with your CV",
        hiringNotes="Source: MelDen hiring creative · Sep 2026.",
        description="Junior & Senior Accountants at MelDen Advisory · Kochi · 2+ yrs · B.Com/M.Com.",
    ),
    job(
        id="ed-tech-customer-relation-executive-kadavanthra-sep2026",
        company="Ed Tech Company",
        companyBlurb="Ed Tech · Customer Relation Executive · Kadavanthra, Kochi",
        location="Kadavanthra, Kochi",
        roles=["Customer Relation Executive"],
        experience="experienced",
        experienceRange="1–3 years",
        employmentType="Full-time",
        tags=["Customer Support", "Ed Tech"],
        email="souravhr43@gmail.com",
        phone="8157078396",
        website="",
        industry="Ed Tech",
        companyDetails="An ed-tech company is hiring a Customer Relation Executive for its Kadavanthra, Kochi office.",
        workDetails="₹15,000–25,000 per month. 1–3 years experience. On-site role only.",
        workStatus="Full-time",
        workMode="On-site · Kadavanthra",
        experienceYears="1–3 years",
        skills=["Customer support", "Communication", "CRM"],
        requirements=[
            "1–3 years of customer relation or support experience",
            "Good communication skills",
            "Must work on-site at Kadavanthra, Kochi",
        ],
        responsibilities=[
            "Handle student and parent queries",
            "Coordinate with internal teams for issue resolution",
            "Maintain customer satisfaction and follow-up records",
        ],
        howToApply="Email souravhr43@gmail.com or call 8157078396",
        hiringNotes="Source: Ed Tech hiring creative · Sep 2026. Company name not printed on poster.",
        description="Customer Relation Executive · Ed Tech · Kadavanthra, Kochi · ₹15k–25k · 1–3 yrs.",
    ),
    job(
        id="travancore-medicity-tutor-nursing-kollam-sep2026",
        company="Travancore Medicity",
        companyBlurb="Travancore Medicity · Tutor (Nursing) · Kollam",
        location="Kollam, Kerala",
        roles=["Tutor (Nursing)"],
        experience="experienced",
        experienceRange="As per institution requirements",
        employmentType="Full-time",
        tags=["Education", "Healthcare", "Nursing"],
        email="careers@tmc.ac.in",
        phone="9495942140",
        website="",
        industry="Healthcare / Education",
        companyDetails="Travancore Medicity is hiring a nursing tutor in Kollam.",
        workDetails="Tutor role for nursing programmes at Travancore Medicity, Kollam.",
        workStatus="Full-time",
        workMode="On-site · Kollam",
        experienceYears="As per institution requirements",
        skills=["Nursing education", "Clinical training", "Teaching"],
        requirements=[
            "Relevant nursing qualification and teaching experience",
            "Registration as applicable",
        ],
        responsibilities=[
            "Deliver nursing theory and practical classes",
            "Guide students in clinical training",
            "Prepare assessments and maintain academic records",
        ],
        howToApply="Email careers@tmc.ac.in or call 9495942140",
        hiringNotes="Source: Travancore Medicity hiring creative · Sep 2026.",
        description="Tutor (Nursing) at Travancore Medicity · Kollam.",
    ),
    job(
        id="sansco-oppo-regional-trainer-kerala-sep2026",
        company="Sansco / OPPO",
        companyBlurb="Sansco · OPPO · Regional Trainer · Cochin, Wayanad, Trivandrum",
        location="Cochin, Wayanad, Trivandrum",
        roles=["Regional Trainer"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Retail", "Training", "Mobile"],
        email="careers.oppo@sansco.in",
        phone="9072587278",
        website="",
        industry="Consumer electronics / Retail",
        companyDetails="Sansco is the OPPO retail partner hiring regional trainers across Kerala.",
        workDetails="Regional Trainer for OPPO retail operations. Locations: Cochin, Wayanad, and Trivandrum.",
        workStatus="Full-time",
        workMode="On-site · Field",
        experienceYears="As per hiring notice",
        skills=["Retail training", "Product knowledge", "Team coaching"],
        requirements=[
            "Experience in retail or mobile sales training",
            "Willingness to travel across assigned region",
        ],
        responsibilities=[
            "Train retail staff on OPPO products and sales",
            "Conduct store-level coaching and assessments",
            "Support launch and promotional activities",
        ],
        howToApply="Email careers.oppo@sansco.in or call 9072587278",
        hiringNotes="Source: Sansco/OPPO hiring creative · Sep 2026.",
        description="Regional Trainer · Sansco/OPPO · Cochin, Wayanad, Trivandrum.",
    ),
    job(
        id="sansco-oppo-visual-merchandiser-alappuzha-kollam-sep2026",
        company="Sansco / OPPO",
        companyBlurb="Sansco · OPPO · Visual Merchandiser · Alappuzha, Kollam",
        location="Alappuzha, Kollam",
        roles=["Visual Merchandiser"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Retail", "Visual Merchandising", "Mobile"],
        email="careers.oppo@sansco.in",
        phone="9072587278",
        website="",
        industry="Consumer electronics / Retail",
        companyDetails="Sansco is hiring visual merchandisers for OPPO retail stores.",
        workDetails="Visual Merchandiser roles at Alappuzha and Kollam.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="As per hiring notice",
        skills=["Visual merchandising", "Retail display", "Branding"],
        requirements=[
            "Experience in retail visual merchandising preferred",
            "Eye for display and brand standards",
        ],
        responsibilities=[
            "Maintain in-store displays and branding",
            "Execute VM guidelines across assigned stores",
            "Coordinate with store teams on launches and promotions",
        ],
        howToApply="Email careers.oppo@sansco.in or call 9072587278",
        hiringNotes="Source: Sansco/OPPO hiring creative · Sep 2026.",
        description="Visual Merchandiser · Sansco/OPPO · Alappuzha, Kollam.",
    ),
    job(
        id="helett-hr-intern-calicut-sep2026",
        company="Helett Enterprises LLP",
        companyBlurb="Helett · HR Intern · Calicut",
        location="Calicut, Kerala",
        roles=["HR Intern"],
        experience="fresher",
        experienceRange="Freshers · Female candidates only",
        employmentType="Internship",
        tags=["HR", "Internship"],
        email="hr@helett.com",
        phone="9946100622",
        website="www.helett.in",
        industry="HR / Recruitment",
        companyDetails="Helett Enterprises LLP is hiring an HR Intern at Calicut. 3-month stipend followed by permanent opportunity.",
        workDetails="Full-time, in-person HR intern role. English mandatory; Hindi preferred. HR qualification preferred. Focus areas: recruitment, LinkedIn, Indeed, HR operations.",
        workStatus="Internship",
        workMode="On-site · Calicut",
        experienceYears="Freshers",
        skills=["Recruitment", "LinkedIn", "Indeed", "HR operations"],
        requirements=[
            "Female candidates only",
            "Freshers can apply",
            "English mandatory; Hindi preferred",
            "HR qualification preferred",
            "Full-time, in-person role",
        ],
        responsibilities=[
            "Support recruitment and sourcing activities",
            "Assist with LinkedIn and Indeed postings",
            "Help with HR operations and documentation",
        ],
        howToApply="Email hr@helett.com or WhatsApp/call 9946100622",
        hiringNotes="Source: Helett hiring creative · Sep 2026.",
        description="HR Intern at Helett · Calicut · Female only · 3-month stipend then permanent.",
    ),
    job(
        id="esaf-healthcare-senior-executive-finance-mannuthy-sep2026",
        company="ESAF Health Care Services",
        companyBlurb="ESAF Health Care · Senior Executive – Finance · Mannuthy",
        location="Mannuthy, Kerala",
        roles=["Senior Executive – Finance"],
        experience="experienced",
        experienceRange="3+ years in healthcare",
        employmentType="Full-time",
        tags=["Finance", "Healthcare"],
        email="careers@esafhealthcare.in",
        phone="8714622595",
        website="",
        industry="Healthcare",
        companyDetails="ESAF Health Care Services is hiring a Senior Executive for its finance team at Mannuthy.",
        workDetails="3+ years in healthcare industry. B.Com or M.Com. GST, TDS, tax returns, financial reporting, MIS, and payroll. 2-wheeler licence required. Candidates from Thrissur or nearby preferred.",
        workStatus="Full-time",
        workMode="On-site · Mannuthy",
        experienceYears="3+ years",
        skills=["GST", "TDS", "Financial reporting", "MIS", "Payroll"],
        requirements=[
            "B.Com or M.Com",
            "3+ years experience in the healthcare industry",
            "GST, TDS & tax returns, financial reporting, MIS, and payroll",
            "2-wheeler licence mandatory",
            "Candidates preferably from Thrissur or nearby locations",
        ],
        responsibilities=[
            "Handle GST, TDS, and tax compliance",
            "Prepare financial reports and MIS",
            "Manage payroll and related finance operations",
        ],
        howToApply="Email careers@esafhealthcare.in or call 8714622595",
        hiringNotes="Source: ESAF Health Care hiring creative · Sep 2026.",
        description="Senior Executive – Finance at ESAF Health Care · Mannuthy · 3+ yrs healthcare.",
    ),
    job(
        id="iic-lakshya-dgm-placements-kochi-sep2026",
        company="Indian Institute of Commerce Lakshya",
        companyBlurb="IIC Lakshya · DGM Placements & Corporate Relations · Kochi",
        location="Kochi, Kerala",
        roles=["DGM – Placements & Corporate Relations"],
        experience="experienced",
        experienceRange="8–12 years",
        employmentType="Full-time",
        tags=["Education", "Placements", "Corporate Relations"],
        email="shan.ks@iiclakshya.com",
        phone="+91 82816 09558",
        website="",
        industry="Education",
        companyDetails="Indian Institute of Commerce Lakshya is hiring a Deputy General Manager for Placements & Corporate Relations in Kochi.",
        workDetails="8–12 years in placement or corporate relations. Lead placement strategy, campus drives, job fairs, and hiring partner network.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="8–12 years",
        skills=["Placements", "Corporate relations", "Campus hiring"],
        requirements=[
            "8–12 years of experience in placement or corporate relations",
            "Strong network of hiring partners",
            "Leadership and stakeholder management skills",
        ],
        responsibilities=[
            "Lead placement strategy and corporate engagements",
            "Develop industry-aligned placement strategies",
            "Drive campus placements, job fairs, and corporate initiatives",
            "Build and expand hiring partner network",
        ],
        howToApply="Email shan.ks@iiclakshya.com or call +91 82816 09558",
        hiringNotes="Source: IIC Lakshya hiring creative · Sep 2026.",
        description="DGM Placements & Corporate Relations at IIC Lakshya · Kochi · 8–12 yrs.",
    ),
    job(
        id="intrcity-railyatri-process-trainer-sep2026",
        company="IntrCity / RailYatri",
        companyBlurb="IntrCity · RailYatri · Process Trainer",
        location="Kerala",
        roles=["Process Trainer"],
        experience="experienced",
        experienceRange="Senior Trainer / Trainer / CQA background",
        employmentType="Full-time",
        tags=["Training", "BPO", "Call Center"],
        email="jofin.jose@intrcity.com",
        phone="9745110007",
        website="",
        industry="Travel / BPO",
        companyDetails="IntrCity and RailYatri are hiring a Process Trainer with call-center training experience.",
        workDetails="Proficiency in Hindi and English required. Previous experience as Senior Trainer, Trainer, or Call Quality Analyst in a call center background.",
        workStatus="Full-time",
        workMode="As per company assignment",
        experienceYears="Relevant training experience",
        skills=["Process training", "Call center", "Hindi", "English", "Quality analysis"],
        requirements=[
            "Proficiency in both Hindi and English",
            "Previous experience as Senior Trainer, Trainer, or Call Quality Analyst",
            "Call center background required",
        ],
        responsibilities=[
            "Train agents on process and quality standards",
            "Conduct refresher and new-hire training batches",
            "Support quality monitoring and coaching",
        ],
        howToApply="Email jofin.jose@intrcity.com or call 9745110007",
        hiringNotes="Source: IntrCity/RailYatri hiring creative · Sep 2026. Location not printed.",
        description="Process Trainer · IntrCity/RailYatri · Hindi & English · Call center training background.",
    ),
    job(
        id="easy-store-telecaller-edappally-sep2026",
        company="easy store",
        companyBlurb="easy store · Telecaller · Edappally, Kochi",
        location="Edappally, Kochi",
        roles=["Telecaller"],
        experience="experienced",
        experienceRange="Minimum 1 year",
        employmentType="Full-time",
        tags=["Telecalling", "Retail"],
        email="KERALA.HR@EASYSTOREMEA.COM",
        phone="8606600068",
        website="",
        address="Easy Store Head Office, 2nd Floor, SK Tower, Near Lulu Mall, Edappally, Ernakulam 682024",
        industry="Retail",
        companyDetails="easy store is hiring telecallers for its Kerala operations. Vacancies across Kerala; walk-in interviews Mon–Fri 10:00 AM–7:00 PM.",
        workDetails="Graduation mandatory. Minimum 1 year telecalling experience. Salary as per company standards. ESI & PF benefits.",
        workStatus="Full-time",
        workMode="On-site · Edappally",
        experienceYears="1+ year",
        skills=["Telecalling", "Communication", "CRM"],
        requirements=[
            "Graduation mandatory",
            "Minimum 1 year experience in telecalling",
        ],
        responsibilities=[
            "Make outbound calls to prospective customers",
            "Follow scripts and achieve calling targets",
            "Update CRM and coordinate with sales teams",
        ],
        howToApply="Walk-in Mon–Fri 10:00 AM–7:00 PM at SK Tower, Edappally, or call 8606600068 / email KERALA.HR@EASYSTOREMEA.COM",
        hiringNotes="Source: easy store hiring creative · Sep 2026.",
        description="Telecaller at easy store · Edappally · Graduation + 1 yr telecalling · Walk-in Mon–Fri.",
    ),
    job(
        id="easy-store-sales-executive-tv-audio-edappally-sep2026",
        company="easy store",
        companyBlurb="easy store · Sales Executive (TV & Audio) · Edappally",
        location="Edappally, Ernakulam",
        roles=["Sales Executive – TV & Audio"],
        experience="both",
        experienceRange="As per company standards",
        employmentType="Full-time",
        tags=["Sales", "Retail", "Electronics"],
        email="",
        phone="8606600068",
        website="",
        industry="Retail / Electronics",
        companyDetails="easy store is hiring a Sales Executive for its TV & Audio section at Edappally.",
        workDetails="Passion for technology, good communication, and drive to achieve. Work with top TV and audio brands. Training, incentives, and stable work environment.",
        workStatus="Full-time",
        workMode="On-site · Edappally showroom",
        experienceYears="As per company standards",
        skills=["Retail sales", "TV & audio products", "Customer service"],
        requirements=[
            "Good communication skills",
            "Interest in consumer electronics",
            "Customer-facing retail experience preferred",
        ],
        responsibilities=[
            "Sell TV and audio products in-store",
            "Assist customers with product selection",
            "Achieve sales targets and upsell accessories",
        ],
        howToApply="Call 8606600068",
        hiringNotes="Source: easy store hiring creative · Sep 2026.",
        description="Sales Executive (TV & Audio) at easy store · Edappally · Call 8606600068.",
    ),
    job(
        id="hsjb-accounts-assistant-kochi-sep2026",
        company="HSJB",
        companyBlurb="HSJB · Accounts Assistant · Kochi",
        location="Kochi, Kerala",
        roles=["Accounts Assistant"],
        experience="both",
        experienceRange="0–1 year",
        employmentType="Full-time",
        tags=["Accounts", "Finance"],
        email="mhrs@hsjbglobal.com",
        phone="",
        website="",
        industry="Recruitment / Staffing / Consulting",
        companyDetails="HSJB (Recruitment | Staffing | Consulting) is hiring an Accounts Assistant in Kochi.",
        workDetails="B.Com or M.Com. 0–1 year experience. Freshers with Tally skills welcome. Support finance and accounting operations.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="0–1 year",
        skills=["Tally", "Accounting", "Bookkeeping", "MS Excel"],
        requirements=[
            "B.Com or M.Com",
            "0–1 year experience; freshers with Tally skills welcome",
            "Detail-oriented with good documentation habits",
        ],
        responsibilities=[
            "Assist with daily accounting and finance activities",
            "Record transactions and handle Tally entries",
            "Maintain ledgers, vouchers, invoices, and records",
            "Help prepare basic financial reports",
        ],
        howToApply='Email mhrs@hsjbglobal.com with subject line "Application – Accounts Assistant"',
        hiringNotes="Source: HSJB hiring creative · Sep 2026.",
        description="Accounts Assistant at HSJB · Kochi · B.Com/M.Com · 0–1 yr · Tally.",
    ),
    job(
        id="senior-accountant-pattimattom-sep2026",
        company="As per hiring creative",
        companyBlurb="Senior Accountant · Pattimattom, Ernakulam",
        location="Pattimattom, Ernakulam District",
        roles=["Senior Accountant"],
        experience="experienced",
        experienceRange="6+ years",
        employmentType="Full-time",
        tags=["Accounts", "Finance"],
        email="pazinohr@gmail.com",
        phone="9895686594",
        website="",
        industry="Accounting",
        companyDetails="Hiring for a Senior Accountant at Pattimattom. Company name not printed on the creative.",
        workDetails="6+ years in accounting or finance. CA or CMA Intermediate preferred. Strong Tally ERP 9 and MS Excel. Auditing experience an advantage. Candidates near Pattimattom preferred.",
        workStatus="Full-time",
        workMode="On-site · Pattimattom",
        experienceYears="6+ years",
        skills=["Tally ERP 9", "MS Excel", "Finalization of accounts", "Auditing"],
        requirements=[
            "6+ years in accounting or finance",
            "CA or CMA Intermediate preferred",
            "Strong Tally ERP 9 and MS Excel",
            "Auditing experience an added advantage",
            "Candidates residing near Pattimattom preferred",
        ],
        responsibilities=[
            "Manage and oversee finalization of accounts",
            "Compile, verify, and review financial information",
            "Ensure accuracy and compliance in financial reporting",
            "Support day-to-day accounting activities",
        ],
        howToApply="Email pazinohr@gmail.com or call 9895686594 with updated CV",
        hiringNotes="Source: hiring creative · Sep 2026. Employer name not printed.",
        description="Senior Accountant · Pattimattom · 6+ yrs · CA/CMA Inter preferred.",
    ),
    job(
        id="hotel-accountant-kochi-sep2026",
        company="Bar-attached Hotel",
        companyBlurb="Hotel · Accountant · Kochi",
        location="Kochi, Kerala",
        roles=["Hotel Accountant"],
        experience="experienced",
        experienceRange="1–2 years",
        employmentType="Full-time",
        tags=["Accounts", "Hospitality"],
        email="",
        phone="8714675014",
        website="",
        industry="Hospitality",
        companyDetails="A bar-attached hotel in Kochi is hiring an accountant. Kochi locals preferred.",
        workDetails="1–2 years hotel accounting experience. Salary ₹18,000–20,000 per month.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="1–2 years",
        skills=["Hotel accounting", "Tally", "Billing"],
        requirements=[
            "1–2 years experience in hotel accounting",
            "Kochi locals preferred",
        ],
        responsibilities=[
            "Handle daily hotel accounting and billing",
            "Maintain books and support month-end closing",
            "Coordinate with front office and F&B on transactions",
        ],
        howToApply="Call 8714675014",
        hiringNotes="Source: hotel hiring creative · Sep 2026. Employer name not printed.",
        description="Hotel Accountant · Kochi · 1–2 yrs · ₹18k–20k · Bar-attached hotel.",
    ),
    job(
        id="lazdana-front-office-associate-bangalore-sep2026",
        company="Lazdana Hotels and Resorts Pvt Ltd",
        companyBlurb="Lazdana · Front Office Associate · Bangalore",
        location="Bangalore, Karnataka",
        roles=["Front Office Associate"],
        experience="experienced",
        experienceRange="Minimum 1 year",
        employmentType="Full-time",
        tags=["Hospitality", "Front Office"],
        email="hr.blr@lazdana.com",
        phone="7902711118",
        website="",
        industry="Hospitality",
        companyDetails="Lazdana Hotels, Resorts, Wellness is hiring a Front Office Associate in Bangalore. Preference for candidates from Kerala and Karnataka.",
        workDetails="Minimum 1 year hotel or hospitality experience. Fluent English and Hindi; Malayalam an advantage. MS Office proficiency.",
        workStatus="Full-time",
        workMode="On-site · Bangalore",
        experienceYears="1+ year",
        skills=["Front office", "Guest relations", "MS Office", "English", "Hindi"],
        requirements=[
            "Minimum 1 year relevant experience in hotel or hospitality",
            "Good communication and interpersonal skills",
            "Fluency in English and Hindi; Malayalam an added advantage",
            "Preference for candidates from Kerala and Karnataka",
        ],
        responsibilities=[
            "Greet and assist guests professionally",
            "Handle check-in and check-out procedures",
            "Manage reservations and guest requests",
            "Provide information on hotel services and local attractions",
        ],
        howToApply="Email hr.blr@lazdana.com or call 7902711118",
        hiringNotes="Source: Lazdana hiring creative · Sep 2026.",
        description="Front Office Associate at Lazdana · Bangalore · 1+ yr hospitality.",
    ),
    job(
        id="chrisma-consultancy-engineer-palakkad-sep2026",
        company="Chrisma Consultancy",
        companyBlurb="Chrisma Consultancy · Engineer (BE/BTech) · Palakkad",
        location="Palakkad City, Kerala",
        roles=["Engineer (BE / B.Tech)"],
        experience="both",
        experienceRange="Freshers to 2 years",
        employmentType="Full-time",
        tags=["Engineering", "Electrical"],
        email="",
        phone="9947337555",
        website="",
        industry="Electrical engineering / Maintenance",
        companyDetails="Chrisma Consultancy is hiring engineers for electrical engineering and maintenance work in Palakkad.",
        workDetails="Diploma-qualified freshers or up to 2 years experience in electrical engineering and maintenance. Salary ₹16,000–20,000 based on performance.",
        workStatus="Full-time",
        workMode="On-site · Palakkad",
        experienceYears="0–2 years",
        skills=["Electrical engineering", "Maintenance", "Field operations"],
        requirements=[
            "BE/B.Tech or Diploma in relevant field",
            "Freshers or up to 2 years experience in electrical engineering and maintenance",
        ],
        responsibilities=[
            "Support electrical engineering and maintenance projects",
            "Inspect and maintain electrical systems",
            "Coordinate with site teams on installations and repairs",
        ],
        howToApply="Call Chrisma Consultancy at 9947337555",
        hiringNotes="Source: Chrisma Consultancy hiring creative · Sep 2026.",
        description="Engineer at Chrisma Consultancy · Palakkad · ₹16k–20k · Electrical maintenance.",
    ),
    job(
        id="chrisma-consultancy-electrician-palakkad-sep2026",
        company="Chrisma Consultancy",
        companyBlurb="Chrisma Consultancy · Electrician / Technician / Wireman · Palakkad",
        location="Palakkad City, Kerala",
        roles=["Electrician", "Technician", "Wireman"],
        experience="experienced",
        experienceRange="ITI Electrician / Wireman",
        employmentType="Full-time",
        tags=["Electrical", "Technician"],
        email="",
        phone="9947337555",
        website="",
        industry="Electrical operations / Maintenance",
        companyDetails="Chrisma Consultancy is hiring electricians, technicians, and wiremen in Palakkad.",
        workDetails="ITI Electrician or Wireman qualification. Experience in electrical operation and maintenance. Salary ₹15,000–18,000 plus ESI and EPF based on performance.",
        workStatus="Full-time",
        workMode="On-site · Palakkad",
        experienceYears="Relevant field experience",
        skills=["Electrical wiring", "Maintenance", "ITI trade"],
        requirements=[
            "ITI Electrician or Wireman qualification",
            "Experience in electrical operation and maintenance",
        ],
        responsibilities=[
            "Execute electrical wiring and maintenance work",
            "Support site operations and troubleshooting",
            "Follow safety standards on active sites",
        ],
        howToApply="Call Chrisma Consultancy at 9947337555",
        hiringNotes="Source: Chrisma Consultancy hiring creative · Sep 2026.",
        description="Electrician/Technician/Wireman at Chrisma · Palakkad · ₹15k–18k + ESI/EPF.",
    ),
    job(
        id="chrisma-consultancy-office-assistant-coimbatore-sep2026",
        company="Chrisma Consultancy",
        companyBlurb="Chrisma Consultancy · Office Assistant (Female) · Coimbatore",
        location="Coimbatore, Tamil Nadu",
        roles=["Office Assistant"],
        experience="both",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Administration"],
        email="",
        phone="9947337555",
        website="",
        industry="Consulting / Administration",
        companyDetails="Chrisma Consultancy is hiring a female Office Assistant at Coimbatore.",
        workDetails="₹15,000 in-hand salary plus food and accommodation provided.",
        workStatus="Full-time",
        workMode="On-site · Coimbatore",
        experienceYears="As per hiring notice",
        skills=["Office administration", "Documentation", "Communication"],
        requirements=[
            "Female candidates only",
            "Willingness to work at Coimbatore",
        ],
        responsibilities=[
            "Support day-to-day office administration",
            "Handle documentation and front-desk tasks",
            "Coordinate with internal teams",
        ],
        howToApply="Call Chrisma Consultancy at 9947337555",
        hiringNotes="Source: Chrisma Consultancy hiring creative · Sep 2026.",
        description="Office Assistant (Female) at Chrisma · Coimbatore · ₹15k in-hand + food & accommodation.",
    ),
    job(
        id="marine-hydrocolloids-graphic-designer-sep2026",
        company="Marine Hydrocolloids",
        companyBlurb="Marine Hydrocolloids · Graphic Designer · MERON",
        location="Kerala",
        roles=["Graphic Designer"],
        experience="both",
        experienceRange="Freshers to 1 year",
        employmentType="Full-time",
        tags=["Design", "Creative", "Marketing"],
        email="hr@meron.com",
        phone="+91 85940 77799",
        website="meron.com",
        industry="FMCG / Packaging / Marketing",
        companyDetails="Marine Hydrocolloids (MERON) is hiring a Graphic Designer for branding, packaging, print, exhibition, and digital marketing.",
        workDetails="Bachelor's or diploma in graphic design or related field. Freshers and up to 1 year experience. Portfolio required. Adobe Photoshop and Illustrator essential.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="0–1 year",
        skills=[
            "Adobe Photoshop",
            "Adobe Illustrator",
            "Packaging design",
            "Print design",
            "Social media creatives",
        ],
        requirements=[
            "Bachelor's degree or diploma in Graphic Design, Visual Communication, Fine Arts, Multimedia, or related field",
            "Freshers and candidates with up to 1 year experience may apply",
            "Portfolio demonstrating design skills required",
            "Adobe Photoshop and Illustrator proficiency",
        ],
        responsibilities=[
            "Design product packaging, labels, and artwork",
            "Create brochures, catalogues, flyers, and corporate materials",
            "Support exhibition booth graphics and event materials",
            "Design social media posts and digital advertisements",
            "Prepare print-ready artwork and maintain brand consistency",
        ],
        howToApply="Email hr@meron.com or hrd@meron.com, or call +91 85940 77799 / +91 90721 77993",
        hiringNotes="Source: Marine Hydrocolloids hiring creative · Sep 2026. Location not printed.",
        description="Graphic Designer at Marine Hydrocolloids (MERON) · Freshers–1 yr · Ps/Ai · Portfolio required.",
    ),
    job(
        id="citroen-multi-roles-trivandrum-sep2026",
        company="Citroën",
        companyBlurb="Citroën · Service & Sales roles · Trivandrum",
        location="Trivandrum, Kerala",
        roles=[
            "Asst. Manager – Service",
            "Service Advisor",
            "Bodyshop Advisor",
            "Technician",
            "Spare Parts Executive",
            "Warranty Executive",
        ],
        experience="both",
        experienceRange="Minimum 2 years · Freshers can apply",
        employmentType="Full-time",
        tags=["Automobile", "Service", "Sales"],
        email="",
        phone="+91 97786 26922",
        website="",
        industry="Automobile",
        companyDetails="Citroën dealership in Trivandrum is hiring across service and related departments.",
        workDetails="ITI, Diploma, or B.Tech. Minimum 2 years relevant automobile industry experience. Freshers may also apply as per poster.",
        workStatus="Full-time",
        workMode="On-site · Trivandrum",
        experienceYears="2+ years preferred",
        skills=["Automobile service", "Customer advisory", "Spare parts", "Warranty"],
        requirements=[
            "ITI, Diploma, or B.Tech qualification",
            "Minimum 2 years relevant experience in automobile industry",
            "Freshers can apply as per hiring creative",
        ],
        responsibilities=[
            "Deliver service, advisory, or parts support as per assigned role",
            "Ensure customer satisfaction and workshop efficiency",
            "Follow Citroën brand and process standards",
        ],
        howToApply="Call +91 97786 26922 or +91 75588 89903",
        hiringNotes="Source: Citroën hiring creative · Sep 2026.",
        description="Multiple roles at Citroën · Trivandrum · Service, parts, warranty · ITI/Diploma/B.Tech.",
    ),
    job(
        id="idfc-first-bharat-rm-gold-loan-walkin-sep18-2026",
        company="IDFC FIRST Bharat",
        companyBlurb="IDFC FIRST Bharat · Relationship Manager – Gold Loan · Walk-in 18 Sep 2026",
        location="Kollam & Kochi (walk-in venues)",
        roles=["Relationship Manager – Gold Loan"],
        experience="both",
        experienceRange="Freshers and experienced",
        employmentType="Full-time",
        applyDeadline="2026-09-18",
        tags=["BFSI", "Sales"],
        isWalkIn=True,
        walkInDate="18 September 2026 · 9:30 AM – 4:00 PM",
        email="",
        phone="9645354643",
        website="www.idfcfirstbharat.com",
        industry="BFSI / Gold loan",
        companyDetails="IDFC FIRST Bharat walk-in recruitment for Relationship Manager – Gold Loan on 18 Sep 2026 at Kollam and Kochi venues.",
        workDetails="Age 21–32. 12th or any degree. Freshers and experienced welcome; gold loan experience preferred. CTC ₹2.50–4.50 LPA plus incentives, PF, ESIC, allowances, and insurance. Vacancies across 27 Kerala locations.",
        workStatus="Full-time",
        workMode="Field / Branch",
        experienceYears="Freshers and experienced",
        skills=["Gold loan sales", "Customer relationship", "Field operations"],
        requirements=[
            "Age 21–32 years",
            "12th pass or any degree",
            "Freshers and experienced candidates may apply",
            "Gold loan experience preferred",
            "Carry Aadhaar, PAN, educational certificates, DL/LLR, photo, experience letter, and payslips",
        ],
        responsibilities=[
            "Acquire and manage gold loan customers",
            "Meet branch and portfolio targets",
            "Ensure compliance with IDFC FIRST Bharat processes",
        ],
        howToApply="Walk-in on 18 Sep 2026, 9:30 AM–4:00 PM. Kollam: IDFC FIRST Bharat Ltd, Regional Office-Kollam, Akelessh Arcade, Kadappakada. Kochi: 1st Floor, Vilayil Building, Near The Tall Tree Furniture, Edappally-Pukkattupady Rd, Unnichira, Thrikkakara. Contact Sujeesh (CBM) 9645354643 or Devika (HR) 8590160153.",
        hiringNotes="Source: IDFC FIRST Bharat walk-in creative · Sep 2026. Drive date may have passed — confirm with HR before travelling.",
        description="RM Gold Loan walk-in · IDFC FIRST Bharat · 18 Sep 2026 · Kollam & Kochi · ₹2.5–4.5 LPA.",
    ),
    job(
        id="palal-group-mass-hiring-kochi-sep2026",
        company="Palal Group",
        companyBlurb="Palal Group · Automobile · Mass hiring · Kochi region",
        location="Netoor, Ernakulam, Thrippunithura, Aluva",
        roles=[
            "General Manager – Service",
            "Manager – Service",
            "Floor Manager",
            "Manager – Spare Parts",
            "Asst. Manager – Warranty",
            "Service Advisor – General",
            "Job Controller",
            "Senior Technician",
            "Technician – General Job",
            "Trainee Technician – General Job",
            "General Manager – Sales",
            "Manager – Sales",
            "Team Leader Sales",
            "Manager – Retail Finance & Insurance",
            "Sales Officer",
            "Accounts Head",
            "Accounts Executives",
            "HR Executive",
            "RTO Coordinator",
            "Delivery Coordinator",
            "MIS Executive",
            "Billing Executive",
            "Insurance Executive",
            "Marketing Incharge",
            "Telecaller",
            "Receptionist",
            "EDP/SSOPI Incharge",
            "Drivers",
        ],
        experience="both",
        experienceRange="Role-specific",
        employmentType="Full-time",
        tags=["Automobile", "Sales", "Service"],
        email="hr.palalauto@gmail.com",
        phone="+91 88910 21202",
        website="",
        industry="Automobile",
        companyDetails="Palal Group is an automobile group in central Kerala partnering with major two-wheeler and four-wheeler brands.",
        workDetails="Openings across service, sales, accounts, HR, insurance, marketing, and support functions at Netoor, Ernakulam, Thrippunithura, and Aluva.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="Role-specific",
        skills=["Automobile sales", "Service operations", "Accounts", "Administration"],
        requirements=[
            "Relevant experience for the applied role",
            "Automobile industry background preferred for technical and sales roles",
        ],
        responsibilities=[
            "Perform duties as per the specific role applied for",
            "Support dealership operations and customer experience",
        ],
        howToApply="Email hr.palalauto@gmail.com or hr@palalmotors.co.in, or call +91 88910 21202 / +91 79070 97074",
        hiringNotes="Source: Palal Group hiring creative · Sep 2026.",
        description="Mass hiring at Palal Group · 28+ roles · Netoor, Ernakulam, Thrippunithura, Aluva.",
    ),
    job(
        id="fedserv-manager-cloud-infosec-kochi-sep2026",
        company="FedServ (Federal Operations & Services Ltd)",
        companyBlurb="FedServ · Manager – Cloud Infrastructure & Information Security · Kochi",
        location="Kochi, Kerala",
        roles=["Manager – Cloud Infrastructure & Information Security"],
        experience="experienced",
        experienceRange="5+ years (3+ years AWS)",
        employmentType="Full-time",
        tags=["Cloud", "Security", "IT"],
        email="amal_fedserv@federalbank.co.in",
        phone="",
        website="",
        industry="BFSI / IT Operations",
        companyDetails="FedServ (Federal Operations & Services Ltd) is hiring a Manager for Cloud Infrastructure and Information Security in Kochi.",
        workDetails="B.E./B.Tech in CS, IT, Electronics, or related field. 5+ years in cloud infrastructure, information security, or IT operations. 3+ years hands-on AWS. Cloud and security certifications preferred (AWS Solutions Architect, SysOps, Security Specialty, CEH, Security+, ISO 27001).",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="5+ years",
        skills=[
            "AWS",
            "Cloud infrastructure",
            "Information security",
            "SIEM",
            "EDR",
            "Vulnerability management",
        ],
        requirements=[
            "B.E./B.Tech – CS, IT, Electronics, or related field",
            "5+ years in cloud infrastructure / information security / IT operations",
            "3+ years hands-on AWS experience",
            "Cloud and security certifications preferred",
            "BFSI/FinTech or regulated-industry exposure an advantage",
        ],
        responsibilities=[
            "Lead secure cloud infrastructure operations",
            "Coordinate vendors and managed service providers",
            "Monitor security tools including SIEM and EDR",
            "Support audits, compliance, and access management",
        ],
        howToApply="Email amal_fedserv@federalbank.co.in with your CV",
        hiringNotes="Source: FedServ hiring creative · Sep 2026. Poster had QR code only; contact from prior FedServ listings.",
        description="Manager Cloud & InfoSec at FedServ · Kochi · 5+ yrs · 3+ yrs AWS.",
    ),
    job(
        id="revivaliq-project-coordinator-edappally-sep2026",
        company="revivaliQ",
        companyBlurb="revivaliQ · Project Coordinator · Edappally, Kochi",
        location="Edappally, Kochi",
        roles=["Project Coordinator"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Project Management", "Operations"],
        email="careers@revivaliq.com",
        phone="9539262408",
        website="",
        industry="Healthcare / Wellness",
        companyDetails="revivaliQ is hiring a Project Coordinator for its Edappally, Kochi office.",
        workDetails="Coordinate projects and cross-functional delivery from the Edappally office.",
        workStatus="Full-time",
        workMode="On-site · Edappally",
        experienceYears="As per hiring notice",
        skills=["Project coordination", "Communication", "Documentation"],
        requirements=[
            "Relevant project coordination experience",
            "Strong organizational and communication skills",
        ],
        responsibilities=[
            "Coordinate project timelines and deliverables",
            "Liaise between teams and stakeholders",
            "Track milestones and reporting",
        ],
        howToApply="Email careers@revivaliq.com or call 9539262408",
        hiringNotes="Source: revivaliQ hiring creative · Sep 2026.",
        description="Project Coordinator at revivaliQ · Edappally, Kochi.",
    ),
    job(
        id="futurespace-consulting-trainer-kochi-sep2026",
        company="Futurespace Consulting",
        companyBlurb="Futurespace Consulting · Trainer · Kochi",
        location="Kochi, Kerala",
        roles=["Trainer"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Training", "Consulting"],
        email="futurespacehr@gmail.com",
        phone="9074093236",
        website="",
        industry="Consulting / Training",
        companyDetails="Futurespace Consulting is hiring a Trainer in Kochi.",
        workDetails="Deliver training programmes for Futurespace Consulting clients and learners.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="As per hiring notice",
        skills=["Training delivery", "Facilitation", "Communication"],
        requirements=[
            "Prior training or facilitation experience",
            "Strong presentation skills",
        ],
        responsibilities=[
            "Design and deliver training sessions",
            "Assess learner progress and provide feedback",
            "Support curriculum updates as needed",
        ],
        howToApply="Email futurespacehr@gmail.com or call 9074093236",
        hiringNotes="Source: Futurespace Consulting hiring creative · Sep 2026.",
        description="Trainer at Futurespace Consulting · Kochi.",
    ),
    job(
        id="eben-telecom-cro-kaloor-sep2026",
        company="Eben Telecom",
        companyBlurb="Eben Telecom · Customer Relation Officer · Kaloor, Kochi",
        location="Kaloor, Kochi",
        roles=["Customer Relation Officer (CRO)"],
        experience="both",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Customer Support", "Telecom"],
        email="sana.kn@ebentelecom.com",
        phone="",
        website="",
        industry="Telecom",
        companyDetails="Eben Telecom is hiring 8 Customer Relation Officers at Kaloor, Kochi.",
        workDetails="8 CRO positions. Salary ₹20,000–22,000 per month.",
        workStatus="Full-time",
        workMode="On-site · Kaloor",
        experienceYears="As per hiring notice",
        skills=["Customer support", "Communication", "Telecom operations"],
        requirements=[
            "Good communication skills",
            "Customer-facing experience preferred",
        ],
        responsibilities=[
            "Handle customer queries and service requests",
            "Support telecom sales and service operations",
            "Maintain customer records and follow-ups",
        ],
        howToApply="Email sana.kn@ebentelecom.com with your CV",
        hiringNotes="Source: Eben Telecom hiring creative · Sep 2026.",
        description="CRO (8 openings) at Eben Telecom · Kaloor · ₹20k–22k.",
    ),
    job(
        id="executive-assistant-chairman-kottayam-kochi-sep2026",
        company="As per hiring creative",
        companyBlurb="Executive Assistant to Chairman · Kottayam & Kochi",
        location="Kottayam & Kochi, Kerala",
        roles=["Executive Assistant to Chairman"],
        experience="experienced",
        experienceRange="3–5 years",
        employmentType="Full-time",
        tags=["Administration", "Executive Support"],
        email="",
        phone="8714675014",
        website="",
        industry="Corporate",
        companyDetails="Hiring an Executive Assistant to the Chairman with travel between Kottayam and Kochi. Company name not printed.",
        workDetails="₹50,000–60,000 per month. 3–5 years experience as Personal Secretary or Executive Assistant.",
        workStatus="Full-time",
        workMode="On-site · Kottayam & Kochi",
        experienceYears="3–5 years",
        skills=["Executive assistance", "Calendar management", "Communication", "Travel coordination"],
        requirements=[
            "3–5 years experience as PS or Executive Assistant",
            "Excellent communication and discretion",
            "Willingness to work across Kottayam and Kochi",
        ],
        responsibilities=[
            "Manage chairman's calendar and correspondence",
            "Coordinate meetings and travel",
            "Handle confidential documentation and follow-ups",
        ],
        howToApply="Call 8714675014",
        hiringNotes="Source: hiring creative · Sep 2026. Employer name not printed.",
        description="Executive Assistant to Chairman · Kottayam & Kochi · ₹50k–60k · 3–5 yrs PS/EA.",
    ),
    job(
        id="altos-technologies-telecaller-infopark-sep2026",
        company="ALTOS Technologies",
        companyBlurb="ALTOS Technologies · Telecaller Executive (Female) · Infopark",
        location="Infopark, Kochi",
        roles=["Telecaller Executive"],
        experience="both",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Telecalling", "IT"],
        email="aiswarya.a@altostechnologies.in",
        phone="",
        website="",
        industry="IT / Software",
        companyDetails="ALTOS Technologies is hiring a female Telecaller Executive at Infopark, Kochi.",
        workDetails="Telecalling role for ALTOS Technologies at Infopark campus.",
        workStatus="Full-time",
        workMode="On-site · Infopark",
        experienceYears="As per hiring notice",
        skills=["Telecalling", "Communication", "Lead generation"],
        requirements=[
            "Female candidates as per hiring creative",
            "Good communication skills",
        ],
        responsibilities=[
            "Make outbound calls for lead generation",
            "Qualify prospects and schedule follow-ups",
            "Maintain call logs and CRM updates",
        ],
        howToApply="Email aiswarya.a@altostechnologies.in",
        hiringNotes="Source: ALTOS Technologies hiring creative · Sep 2026.",
        description="Telecaller Executive (Female) at ALTOS Technologies · Infopark.",
    ),
    job(
        id="firstcry-marketing-executive-kochi-sep2026",
        company="FirstCry",
        companyBlurb="FirstCry · Marketing Executive · Kochi",
        location="Kochi, Kerala",
        roles=["Marketing Executive"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Marketing", "Retail"],
        email="bipin.baby@firstcry.com",
        phone="7560846126",
        website="",
        industry="Retail / E-commerce",
        companyDetails="FirstCry is hiring a Marketing Executive in Kochi.",
        workDetails="Support marketing campaigns and retail activations for FirstCry in Kochi.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="As per hiring notice",
        skills=["Marketing", "Campaign execution", "Retail promotions"],
        requirements=[
            "Relevant marketing experience",
            "Good communication and execution skills",
        ],
        responsibilities=[
            "Execute local marketing campaigns",
            "Coordinate promotions and store activations",
            "Track campaign performance and reporting",
        ],
        howToApply="Email bipin.baby@firstcry.com or call 7560846126",
        hiringNotes="Source: FirstCry hiring creative · Sep 2026.",
        description="Marketing Executive at FirstCry · Kochi.",
    ),
    job(
        id="san-fegan-biotech-associate-scientific-service-sep2026",
        company="San Fegan Biotech",
        companyBlurb="San Fegan Biotech · Associate – Scientific Service · Calicut, Kochi, TVM",
        location="Calicut, Kochi, Thiruvananthapuram",
        roles=["Associate – Scientific Service"],
        experience="experienced",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Biotech", "Scientific", "Sales Support"],
        email="hr@sanfegan.com",
        phone="9745729080",
        website="",
        industry="Biotechnology",
        companyDetails="San Fegan Biotech is hiring Associates for Scientific Service across Calicut, Kochi, and Thiruvananthapuram.",
        workDetails="Scientific service and customer support role across three Kerala cities.",
        workStatus="Full-time",
        workMode="Field / On-site",
        experienceYears="As per hiring notice",
        skills=["Scientific support", "Product knowledge", "Customer service"],
        requirements=[
            "Relevant life sciences or biotech background",
            "Good communication and field travel ability",
        ],
        responsibilities=[
            "Provide scientific support to customers and partners",
            "Demonstrate products and handle technical queries",
            "Coordinate with sales and technical teams",
        ],
        howToApply="Email hr@sanfegan.com or call 9745729080",
        hiringNotes="Source: San Fegan Biotech hiring creative · Sep 2026.",
        description="Associate – Scientific Service at San Fegan Biotech · Calicut, Kochi, TVM.",
    ),
    job(
        id="six-guards-sales-coordinator-sep2026",
        company="Six Guards",
        companyBlurb="Six Guards · Sales Coordinator",
        location="Kerala",
        roles=["Sales Coordinator"],
        experience="experienced",
        experienceRange="3+ years · Age 25+",
        employmentType="Full-time",
        tags=["Sales", "Coordination"],
        email="hr@sixguards.com",
        phone="9249135937",
        website="",
        industry="Security / Services",
        companyDetails="Six Guards is hiring a Sales Coordinator.",
        workDetails="3+ years experience. Age 25+. B2B and B2C sales coordination experience mandatory.",
        workStatus="Full-time",
        workMode="As per company assignment",
        experienceYears="3+ years",
        skills=["Sales coordination", "B2B", "B2C", "CRM"],
        requirements=[
            "Minimum 3 years experience",
            "Age 25 years and above",
            "B2B and B2C sales coordination experience mandatory",
        ],
        responsibilities=[
            "Coordinate sales activities across B2B and B2C channels",
            "Support proposals, follow-ups, and order processing",
            "Liaise between sales team and operations",
        ],
        howToApply="Email hr@sixguards.com or call 9249135937",
        hiringNotes="Source: Six Guards hiring creative · Sep 2026. Location not printed.",
        description="Sales Coordinator at Six Guards · 3+ yrs · Age 25+ · B2B/B2C coordination.",
    ),
    job(
        id="kaippoorikkara-lady-staff-roles-kochi-sep2026",
        company="Kaippoorikkara (Resort/Hotel)",
        companyBlurb="Kaippoorikkara · Lady staff · 5 roles · Kochi",
        location="Kaippoorikkara, Kochi",
        roles=[
            "Front Office",
            "Housekeeping",
            "Kitchen Staff",
            "Service Staff",
            "Administration",
        ],
        experience="both",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Hospitality", "Hotel"],
        email="",
        phone="9526206468",
        website="",
        industry="Hospitality",
        companyDetails="A property at Kaippoorikkara, Kochi is hiring female staff across five departments.",
        workDetails="Lady staff required for front office, housekeeping, kitchen, service, and administration roles.",
        workStatus="Full-time",
        workMode="On-site · Kaippoorikkara",
        experienceYears="As per hiring notice",
        skills=["Hospitality", "Guest service", "Housekeeping", "Kitchen operations"],
        requirements=[
            "Female candidates only",
            "Relevant experience preferred for applied role",
            "Willingness to work at Kaippoorikkara, Kochi",
        ],
        responsibilities=[
            "Perform duties as per the department applied for",
            "Support daily hotel/resort operations",
        ],
        howToApply="WhatsApp or call 9526206468",
        hiringNotes="Source: Kaippoorikkara hiring creative · Sep 2026. Exact employer name not printed.",
        description="Lady staff (5 roles) · Kaippoorikkara, Kochi · Front office, HK, kitchen, service, admin.",
    ),
    job(
        id="telecaller-female-kadavanthra-sep2026",
        company="As per hiring creative",
        companyBlurb="Telecaller (Female) · Kadavanthra, Kochi",
        location="Kadavanthra, Kochi",
        roles=["Telecaller"],
        experience="both",
        experienceRange="As per hiring notice",
        employmentType="Full-time",
        tags=["Telecalling"],
        email="",
        phone="8921241429",
        website="",
        industry="Not specified",
        companyDetails="Hiring a female telecaller at Kadavanthra, Kochi. Company name not printed on poster.",
        workDetails="Female telecaller role at Kadavanthra, Kochi.",
        workStatus="Full-time",
        workMode="On-site · Kadavanthra",
        experienceYears="As per hiring notice",
        skills=["Telecalling", "Communication"],
        requirements=[
            "Female candidates as per hiring creative",
            "Good communication skills",
        ],
        responsibilities=[
            "Make outbound calls as per campaign scripts",
            "Update leads and follow-up records",
        ],
        howToApply="Call 8921241429 or 7736987162",
        hiringNotes="Source: hiring creative · Sep 2026. Employer name not printed.",
        description="Telecaller (Female) · Kadavanthra, Kochi.",
    ),
    job(
        id="idexcel-plm-teamcenter-developer-sep2026",
        company="ID Excel",
        companyBlurb="ID Excel · PLM Teamcenter Developer · Pune / Remote",
        location="Pune (preferred) / Remote",
        roles=["PLM Teamcenter Developer"],
        experience="experienced",
        experienceRange="6–8 years",
        employmentType="Full-time",
        tags=["PLM", "Teamcenter", "IT"],
        email="sandra.p@idexcel.com",
        phone="",
        website="",
        industry="IT / PLM",
        companyDetails="ID Excel is hiring a PLM Teamcenter Developer. Pune preferred; remote possible.",
        workDetails="6–8 years PLM Teamcenter development experience. Budget as printed on creative.",
        workStatus="Full-time",
        workMode="Pune preferred / Remote",
        experienceYears="6–8 years",
        skills=["PLM", "Teamcenter", "Customization", "Integration"],
        requirements=[
            "6–8 years experience in PLM Teamcenter development",
            "Strong customization and integration skills",
        ],
        responsibilities=[
            "Develop and customize Teamcenter solutions",
            "Support PLM integrations and enhancements",
            "Collaborate with client teams on requirements",
        ],
        howToApply="Email sandra.p@idexcel.com with your CV",
        hiringNotes="Source: ID Excel hiring creative · Sep 2026.",
        description="PLM Teamcenter Developer at ID Excel · 6–8 yrs · Pune/Remote.",
    ),
    job(
        id="gulffast-fullstack-developer-intern-kozhikode-sep2026",
        company="Gulffast",
        companyBlurb="Gulffast · Fullstack Developer Intern · Kozhikode region",
        location="Kozhikode region, Kerala",
        roles=["Fullstack Developer Intern"],
        experience="fresher",
        experienceRange="Internship",
        employmentType="Internship",
        tags=["Internship", "Full Stack", "IT"],
        email="rental@gulffast.co",
        phone="",
        website="",
        industry="Technology",
        companyDetails="Gulffast is hiring a Fullstack Developer Intern in the Kozhikode region.",
        workDetails="Internship role working with Next.js, TypeScript, Tailwind CSS, PostgreSQL, and Prisma.",
        workStatus="Internship",
        workMode="On-site / Hybrid · Kozhikode region",
        experienceYears="Internship / Fresher",
        skills=[
            "Next.js",
            "TypeScript",
            "Tailwind CSS",
            "PostgreSQL",
            "Prisma",
        ],
        requirements=[
            "Interest in full-stack web development",
            "Familiarity with modern JavaScript/TypeScript stack",
            "Based in or willing to work in Kozhikode region",
        ],
        responsibilities=[
            "Build and maintain web application features",
            "Work with Next.js, TypeScript, and PostgreSQL stack",
            "Collaborate with the development team on product tasks",
        ],
        howToApply="Email rental@gulffast.co with your CV and portfolio/GitHub",
        hiringNotes="Source: Gulffast hiring creative · Sep 2026.",
        description="Fullstack Developer Intern at Gulffast · Next.js/TS/Tailwind/Prisma · Kozhikode region.",
    ),
]


def main() -> None:
    n = mod.insert_jobs(ROOT / "data" / "jobs-data.js", "JOBS", JOBS)
    print(f"Added {n} WhatsApp jobs to jobs-data.js")


if __name__ == "__main__":
    main()
