#!/usr/bin/env python3
"""Add curated IT & Non-IT jobs from WhatsApp / direct employer posts (Sep 2026)."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "import_park_jobs", ROOT / "scripts" / "import-park-jobs-latest.py"
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

NOTE = mod.NOTE
TODAY = mod.TODAY.isoformat()


def direct_job(**kwargs) -> dict:
    base = {
        "logo": "",
        "postedDate": TODAY,
        "source": "WhatsApp",
        "verified": True,
        "verificationNote": NOTE,
        "isWalkIn": False,
        "walkInDate": "",
        "startingDate": "",
        "skills": [],
    }
    base.update(kwargs)
    return base


DIRECT_JOBS = [
    direct_job(
        id="riafy-project-coordinator-kochi-sep2026",
        company="RIAFY",
        companyBlurb="RIAFY · Project Coordinator · Kochi · Freshers welcome",
        location="Infopark, Kochi",
        roles=["Project Coordinator"],
        experience="fresher",
        experienceRange="Freshers welcome",
        employmentType="Full-time",
        applyLink="mailto:jobs@riafy.me",
        applyDeadline="2026-09-20",
        tags=["IT"],
        email="jobs@riafy.me",
        website="",
        address="Kochi, Kerala",
        industry="IT Services",
        companyDetails="RIAFY is hiring a Project Coordinator in Kochi. Coordinate with clients and teams, track timelines, and support project delivery.",
        workDetails="Client communication, team coordination, timeline tracking, stakeholder follow-ups, documentation, and risk identification. Freshers encouraged.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="Freshers welcome",
        requirements=[
            "Excellent written and verbal communication",
            "Strong coordination and organization",
            "Problem-solving and attention to detail",
            "No prior project management experience required",
        ],
        responsibilities=[
            "Client communication and requirement clarification",
            "Team and task coordination",
            "Timeline and project tracking",
            "Stakeholder follow-ups and documentation",
        ],
        howToApply="Email your resume to jobs@riafy.me with subject: Project Coordinator – Kochi.",
        hiringNotes="Source: employer WhatsApp creative · Sep 2026. Verify details with RIAFY before applying.",
        description="RIAFY — Project Coordinator in Kochi. Freshers welcome.",
    ),
    direct_job(
        id="instance-it-graphic-designer-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · Graphic Designer · 1+ year · Full-time",
        location="Kochi, Kerala",
        roles=["Graphic Designer"],
        experience="experienced",
        experienceRange="1+ year",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["Design"],
        email="career@instanceit.com",
        phone="7990231399",
        address="Kochi, Kerala",
        industry="IT Services",
        companyDetails="Instance IT Solutions is hiring across design, development, QA, and business development.",
        workDetails="Graphic Designer · 1+ year experience · 1 opening · 5-day work week.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="1+ year",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026.",
        description="Graphic Designer at Instance IT Solutions — 1+ year.",
    ),
    direct_job(
        id="instance-it-video-editor-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · Video Editor · 2+ years",
        location="Kochi, Kerala",
        roles=["Video Editor"],
        experience="experienced",
        experienceRange="2+ years",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["Design"],
        email="career@instanceit.com",
        phone="7990231399",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026.",
        description="Video Editor at Instance IT Solutions — 2+ years.",
    ),
    direct_job(
        id="instance-it-bde-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · Business Development Executive · 1+ year · 2 openings",
        location="Kochi, Kerala",
        roles=["Business Development Executive"],
        experience="experienced",
        experienceRange="1+ year",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["Sales"],
        email="career@instanceit.com",
        phone="7990231399",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026 · 2 openings.",
        description="BDE at Instance IT Solutions — 1+ year.",
    ),
    direct_job(
        id="instance-it-nodejs-developer-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · Node.js Developer · 2+ years · 2 openings",
        location="Kochi, Kerala",
        roles=["Node.js Developer"],
        experience="experienced",
        experienceRange="2+ years",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["IT"],
        email="career@instanceit.com",
        phone="7990231399",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026 · 2 openings.",
        description="Node.js Developer at Instance IT Solutions.",
    ),
    direct_job(
        id="instance-it-flutter-developer-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · Flutter Developer · 1+ year · 2 openings",
        location="Kochi, Kerala",
        roles=["Flutter Developer"],
        experience="experienced",
        experienceRange="1+ year",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["IT"],
        email="career@instanceit.com",
        phone="7990231399",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026 · 2 openings.",
        description="Flutter Developer at Instance IT Solutions.",
    ),
    direct_job(
        id="instance-it-qa-sep2026",
        company="Instance IT Solutions",
        companyBlurb="Instance IT Solutions · QA Engineer · 1+ year",
        location="Kochi, Kerala",
        roles=["QA Engineer"],
        experience="experienced",
        experienceRange="1+ year",
        employmentType="Full-time",
        applyLink="mailto:career@instanceit.com",
        applyDeadline="2026-09-25",
        tags=["IT"],
        email="career@instanceit.com",
        phone="7990231399",
        howToApply="Email career@instanceit.com or call 7990231399.",
        hiringNotes="Source: Instance IT hiring creative · Sep 2026.",
        description="QA Engineer at Instance IT Solutions.",
    ),
    direct_job(
        id="90plus-mytuitionapp-hr-trainees-walkin-sept10-2026",
        company="90+ My Tuition App",
        companyBlurb="90+ My Tuition App · HR Trainees · Walk-in 10 Sep 2026 · Infopark Koratty",
        location="Infopark Koratty, Thrissur",
        roles=["HR Trainees"],
        experience="fresher",
        experienceRange="MBA · Fresher with internship certification",
        employmentType="Full-time",
        applyLink="mailto:hr@mytuitionapp.com",
        applyDeadline="2026-09-10",
        tags=["HR"],
        isWalkIn=True,
        walkInDate="Wednesday, 10 September 2026 · 10:30 AM – 3:30 PM",
        email="hr@mytuitionapp.com",
        phone="7558899222",
        website="https://www.mytuitionapp.com",
        address="Ground Floor, Indeevaram, Infopark Campus, Koratty, Thrissur",
        industry="EdTech",
        companyDetails="90+ My Tuition App — HR Trainees walk-in at Infopark Koratty.",
        workDetails="Walk-in on 10 Sep 2026, 10:30 AM–3:30 PM. MBA freshers with internship certification. Good communication skills required.",
        workStatus="Full-time",
        workMode="On-site · Infopark Koratty",
        experienceYears="Fresher",
        requirements=[
            "MBA qualification",
            "Fresher with internship certification",
            "Good communication skills",
        ],
        howToApply="Walk in on 10 Sep 2026 (10:30 AM–3:30 PM) at Ground Floor, Indeevaram, Infopark Campus, Koratty. Carry resume, Aadhar, certificates, internship proof, photo, and ID.",
        hiringNotes="Source: employer walk-in flyer · Sep 2026. Call 7558899222 to confirm before travel.",
        description="HR Trainees walk-in — 90+ My Tuition App, Infopark Koratty, 10 Sep 2026.",
    ),
    direct_job(
        id="limenzy-seo-executive-cyberpark-sep2026",
        company="Limenzy Technologies Pvt Ltd",
        companyBlurb="Limenzy Technologies · SEO Executive · 1–2 years · Cyberpark Calicut",
        location="Cyberpark, Kozhikode",
        roles=["SEO Executive"],
        experience="experienced",
        experienceRange="1–2 years",
        employmentType="Full-time",
        applyLink="mailto:hr@limenzy.com",
        applyDeadline="2026-09-20",
        tags=["Marketing", "IT"],
        email="hr@limenzy.com",
        phone="9495026688",
        address="Govt. Cyberpark, Calicut, Kerala",
        industry="IT Services",
        companyDetails="Limenzy Technologies Pvt Ltd — SEO Executive at Cyberpark Kozhikode.",
        workDetails="SEO Executive · 1–2 years experience. Male candidates preferred per employer posting — verify on official channel.",
        workStatus="Full-time",
        workMode="On-site · Cyberpark Kozhikode",
        experienceYears="1–2 years",
        howToApply="Email CV to hr@limenzy.com or contact@silmenty.com · Call 9495026688.",
        hiringNotes="Source: Cyberpark hiring flyer · Sep 2026.",
        description="SEO Executive — Limenzy Technologies, Cyberpark Calicut.",
    ),
    direct_job(
        id="cronus-steel-sds2-detailers-cyberpark-sep2026",
        company="Cronus Steel Detailing",
        companyBlurb="Cronus Steel · SDS2 Detailers · Cyberpark Calicut",
        location="Cyberpark, Kozhikode",
        roles=["SDS2 Detailers"],
        experience="both",
        experienceRange="As per employer posting",
        employmentType="Full-time",
        applyLink="https://www.cronussteel.com",
        applyDeadline="2026-09-25",
        tags=["IT"],
        website="https://www.cronussteel.com",
        address="Govt. Cyberpark, Calicut, Kerala",
        industry="Engineering / Steel detailing",
        companyDetails="Cronus Steel Detailing — global steel detailing projects from Cyberpark Kozhikode.",
        workDetails="SDS2 Detailers · work on global projects · grow with experts.",
        workStatus="Full-time",
        workMode="On-site · Cyberpark Kozhikode",
        howToApply="Apply via www.cronussteel.com or Cyberpark listing.",
        hiringNotes="Source: Cyberpark hiring flyer · Sep 2026.",
        description="SDS2 Detailers at Cronus Steel — Cyberpark Calicut.",
    ),
    direct_job(
        id="edusolve-sales-head-hybrid-sep2026",
        company="Edu Solve",
        companyBlurb="Edu Solve · Sales Head · Female · 2+ years edtech · Hybrid",
        location="Kerala · Hybrid",
        roles=["Sales Head"],
        experience="experienced",
        experienceRange="2+ years in edtech",
        employmentType="Full-time",
        applyLink="https://www.edusolvelearn.com",
        applyDeadline="2026-09-20",
        tags=["Sales"],
        phone="9497085892",
        website="https://www.edusolvelearn.com",
        industry="EdTech",
        companyDetails="Edu Solve — immediate hiring for Sales Head (female candidates per employer post).",
        workDetails="Hybrid role · 2+ years edtech experience · proven target achievement · laptop mandatory.",
        workStatus="Full-time",
        workMode="Hybrid",
        experienceYears="2+ years edtech",
        salaryRange="Attractive salary + incentives",
        requirements=[
            "Female candidates (per employer posting)",
            "Two years experience in edtech",
            "Proven target achievement record",
            "Laptop mandatory",
            "Good communication and leadership skills",
        ],
        howToApply="Visit www.edusolvelearn.com or call +91 9497085892.",
        hiringNotes="Source: employer hiring creative · Sep 2026.",
        description="Sales Head — Edu Solve · Hybrid · edtech.",
    ),
    direct_job(
        id="blastline-female-accountant-angamaly-sep2026",
        company="Blastline India Pvt Ltd",
        companyBlurb="Blastline India · Female Accountant · 2+ years · Inkel Business Park Angamaly",
        location="Inkel Business Park, Angamaly, Kerala",
        roles=["Accountant"],
        experience="experienced",
        experienceRange="2+ years · B.Com minimum",
        employmentType="Full-time",
        applyLink="mailto:hr@blastlineindia.com",
        applyDeadline="2026-09-25",
        tags=["HR"],
        email="hr@blastlineindia.com",
        address="Inkel Business Park, Angamaly, Kerala 683573",
        industry="Manufacturing",
        companyDetails="Blastline India Pvt Ltd — manufacturing excellence in marine, infrastructure, oil & gas, and more.",
        workDetails="Female Accountant · min B.Com · 2+ years accounting · Tally & GST · manufacturing unit experience preferred.",
        workStatus="Full-time",
        workMode="On-site · Angamaly",
        experienceYears="2+ years",
        requirements=[
            "Minimum B.Com",
            "2+ years accounting experience",
            "Tally and GST knowledge",
            "MS Excel skills",
            "Manufacturing unit experience preferred",
        ],
        howToApply="Email resume to hr@blastlineindia.com",
        hiringNotes="Source: employer hiring creative · Sep 2026.",
        description="Female Accountant — Blastline India, Angamaly.",
    ),
    direct_job(
        id="field-sales-executive-kozhikode-paint-sep2026",
        company="Leading Paint Company",
        companyBlurb="Field Sales Executive · Kozhikode · Up to 3 LPA + TA · Bike mandatory",
        location="Kozhikode, Kerala",
        roles=["Field Sales Executive"],
        experience="both",
        experienceRange="Freshers & experienced",
        employmentType="Full-time",
        applyLink="tel:+919040208278",
        applyDeadline="2026-09-15",
        tags=["Sales"],
        phone="9040208278",
        industry="Paint / FMCG",
        companyDetails="Leading paint industry company hiring Field Sales Executive in Kozhikode.",
        workDetails="Convert leads, site supervision, quotations, follow-ups, lead generation. Male candidates · bike & DL mandatory.",
        workStatus="Full-time",
        workMode="Field · Kozhikode",
        salaryRange="Up to ₹3 LPA + TA",
        requirements=[
            "Male candidates only (per employer posting)",
            "Bike and driving licence mandatory",
            "Freshers and experienced welcome",
        ],
        howToApply="Telephonic interview — call 9040208278.",
        hiringNotes="Source: WhatsApp hiring alert · Sep 2026. Verify employer name before applying.",
        description="Field Sales Executive — Kozhikode · paint industry.",
    ),
    direct_job(
        id="simelabs-python-react-fullstack-direct-sep2026",
        company="Simelabs - An Astek Company",
        companyBlurb="Simelabs · Python – React Fullstack · 5+ years · Infopark Kochi",
        location="Infopark, Kochi",
        roles=["Python – React Fullstack"],
        experience="experienced",
        experienceRange="5+ years",
        employmentType="Full-time",
        applyLink="mailto:hr@simelabs.com",
        applyDeadline="2026-09-19",
        tags=["IT"],
        email="hr@simelabs.com",
        address="Infopark, Kochi, Kerala",
        industry="IT Services",
        companyDetails="Simelabs – An Astek Company · Python React Fullstack role at Infopark Kochi.",
        workDetails="5+ years · Python, FastAPI, REST APIs · React.js, TypeScript · PostgreSQL/MySQL.",
        workStatus="Full-time",
        workMode="On-site · Infopark Kochi",
        experienceYears="5+ years",
        skills=["Python", "FastAPI", "React.js", "TypeScript", "PostgreSQL", "MySQL"],
        requirements=[
            "5+ years software engineering experience",
            "Python, FastAPI & REST APIs",
            "React.js, TypeScript & JavaScript",
            "PostgreSQL / MySQL",
        ],
        howToApply="Send resume to hr@simelabs.com",
        hiringNotes="Source: Simelabs direct hiring post · Sep 2026. Also check infopark.in listing.",
        description="Python React Fullstack — Simelabs, Infopark Kochi · 5+ years.",
    ),
    direct_job(
        id="armia-rhce-linux-walkin-reminder-sep2-2026",
        company="Armia Systems Inc.",
        companyBlurb="Armia Systems · RHCE Linux System Engineer · Walk-in 2 Sep 2026 · Infopark Phase 2",
        location="Infopark Phase 2, Kakkanad, Kochi",
        roles=["RHCE Certified Linux System Engineer (Fresher)"],
        experience="fresher",
        experienceRange="RHCE certified fresher",
        employmentType="Internship",
        applyLink="mailto:jobs@armia.com",
        applyDeadline="2026-09-02",
        tags=["IT"],
        isWalkIn=True,
        walkInDate="Tuesday, 2 September 2026 · 10:00 AM – 3:00 PM",
        email="jobs@armia.com",
        phone="8590136418",
        address="3rd Floor, Jyothirmaya Building, Infopark Phase 2, Kakkanad, Kerala 682303",
        companyDetails="Armia Systems Inc. — RHCE Linux walk-in for freshers at Infopark Phase 2.",
        workDetails="Walk-in 2 Sep 2026 · RHCE / Red Hat Certified Engineer fresher · Linux, networking, shell scripting.",
        workStatus="Internship / Fresher",
        workMode="On-site · Infopark Phase 2",
        requirements=[
            "RHCE certified or Red Hat Certified Engineer (fresher)",
            "Strong Linux fundamentals",
            "Basic networking and shell scripting",
        ],
        howToApply="Walk in on 2 Sep 2026, 10 AM–3 PM at Jyothirmaya Building, Infopark Phase 2. Email jobs@armia.com · Deepak OS: 8590136418.",
        hiringNotes="Source: Armia walk-in reminder · Sep 2026. Verify walk-in still active on official channel.",
        description="RHCE Linux Engineer walk-in — Armia Systems, Infopark Phase 2, 2 Sep 2026.",
    ),
]


def main() -> None:
    n = mod.insert_jobs(ROOT / "data" / "jobs-data.js", "JOBS", DIRECT_JOBS)
    print(f"Added {n} direct jobs to jobs-data.js")


if __name__ == "__main__":
    main()
