#!/usr/bin/env python3
"""Add WhatsApp hiring creatives collected 7–15 Sep 2026."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "import_park_jobs", ROOT / "scripts" / "import-park-jobs-latest.py"
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

NOTE = mod.NOTE
POSTED = "2026-09-16"


def job(**kwargs) -> dict:
    base = {
        "logo": "",
        "postedDate": POSTED,
        "source": "WhatsApp",
        "verified": True,
        "verificationNote": NOTE,
        "isWalkIn": False,
        "walkInDate": "",
        "startingDate": "",
        "skills": [],
        "applyDeadline": "Rolling",
        "benefits": [
            "Listing transcribed from an employer hiring creative",
            "Never pay anyone for this application",
        ],
    }
    base.update(kwargs)
    return base


JOBS = [
    job(
        id="fedserv-phone-banking-officers-walkin-sep18-2026",
        company="FedServ (Federal Operations & Services Ltd)",
        companyBlurb="FedServ · Phone Banking Officers · Walk-in 18 Sep 2026 · Carnival Infopark Phase 1, Kochi",
        location="Carnival Infopark Phase 1, Kakkanad, Kochi",
        roles=["Phone Banking Officer"],
        experience="both",
        experienceRange="As per walk-in notice",
        employmentType="Full-time",
        applyLink="https://maps.google.com/?q=Carnival+Infopark+Phase+1,+Kakkanad",
        applyDeadline="2026-09-18",
        tags=["Business"],
        isWalkIn=True,
        walkInDate="18 September 2026 · Reporting 10:00 AM",
        email="",
        phone="",
        website="",
        address="Federal Operations and Services Ltd, Ground Floor, Carnival Infopark Phase 1, Kakkanad, Kochi 682042",
        industry="BFSI / Operations",
        companyDetails="FedServ (Federal Operations & Services Ltd) is a wholly owned subsidiary of Federal Bank. Walk-in hiring at Carnival Infopark Phase 1, Kakkanad.",
        workDetails="Phone Banking Officers in Kochi. Handle inbound and outbound banking-support calls, share product/service information, resolve customer issues, and follow banking regulations. Rotational shifts. Strong English required; Hindi and other regional languages attract additional allowance.",
        workStatus="Full-time",
        workMode="On-site · Carnival Infopark Phase 1",
        experienceYears="As per walk-in notice",
        skills=["English communication", "Customer support", "Banking operations"],
        requirements=[
            "Excellent communication skills in English",
            "Fluency in Hindi and other regional languages will attract additional allowance",
            "Willingness to work in rotational shifts",
            "Walk in on 18 Sep 2026 at 10:00 AM with documents as required by FedServ",
        ],
        responsibilities=[
            "Handle inbound and outbound calls for banking support",
            "Provide product and service information",
            "Resolve customer issues efficiently",
            "Ensure compliance with banking regulations",
        ],
        howToApply="Walk-in on 18 September 2026, reporting 10:00 AM, at Federal Operations and Services Ltd, Ground Floor, Carnival Infopark Phase 1, Kakkanad, Kochi 682042.",
        hiringNotes="Source: FedServ walk-in creative · Sep 2026. Confirm the drive with FedServ before travelling.",
        description="FedServ Phone Banking Officers walk-in — 18 Sep 2026, Carnival Infopark Phase 1, Kochi.",
    ),
    job(
        id="fedserv-hr-executive-officer-kochi-sep2026",
        company="FedServ (Federal Operations & Services Ltd)",
        companyBlurb="FedServ · HR Executive / HR Officer · 1–2 years · Carnival Infopark, Kochi",
        location="Carnival Infopark Phase 1, Kakkanad, Kochi",
        roles=["HR Executive / HR Officer"],
        experience="experienced",
        experienceRange="1–2 years",
        employmentType="Full-time",
        applyLink="mailto:amal_fedserv@federalbank.co.in?subject=HR%20Executive%20%2F%20HR%20Officer",
        tags=["HR", "Business"],
        email="amal_fedserv@federalbank.co.in",
        address="Ground Floor, Carnival Infopark Phase 1, Kakkanad, Kochi 682042",
        industry="BFSI / Operations",
        companyDetails="FedServ (Federal Operations & Services Ltd), a wholly owned subsidiary of Federal Bank, is hiring HR at Carnival Infopark Phase 1, Kochi.",
        workDetails="HR Executive / HR Officer · 1–2 years. Drive recruitment and onboarding, support daily HR operations, manage payroll inputs and leave tracking, and lead employee engagement and welfare activities.",
        workStatus="Full-time",
        workMode="On-site · Carnival Infopark Phase 1",
        experienceYears="1–2 years",
        skills=["Recruitment", "HR operations", "Payroll", "Employee engagement"],
        requirements=[
            "1–2 years HR experience as listed on the hiring creative",
            "Comfortable with recruitment, onboarding, payroll inputs, and leave tracking",
        ],
        responsibilities=[
            "Drive recruitment and onboarding",
            "Support daily HR operations",
            "Manage payroll inputs and leave tracking",
            "Lead employee engagement and welfare activities",
        ],
        howToApply="Email your resume to amal_fedserv@federalbank.co.in. Poster also includes a scan-to-apply QR — use the email if you cannot scan it.",
        hiringNotes="Source: FedServ HR hiring creative · Sep 2026. Verify with the employer before applying.",
        description="HR Executive / HR Officer at FedServ, Carnival Infopark Kochi · 1–2 years.",
    ),
    job(
        id="maple-tech-space-client-marketing-coordinator-koratty-sep2026",
        company="Maple Tech Space",
        companyBlurb="Maple Tech Space · Client Marketing Coordinator · 2–3 years · Night shift · Infopark Koratty",
        location="Infopark Koratty, Thrissur",
        roles=["Client Marketing Coordinator"],
        experience="experienced",
        experienceRange="2–3 years",
        employmentType="Full-time",
        applyLink="mailto:careers@mapletechspace.com?subject=Client%20Marketing%20Coordinator",
        tags=["Marketing"],
        email="careers@mapletechspace.com",
        address="Infopark, Koratty",
        industry="IT / Marketing operations",
        companyDetails="Maple Tech Space is hiring a Client Marketing Coordinator at Infopark, Koratty.",
        workDetails="2–3 years experience. Shift 6:00 pm to 3:00 am. Work from office at Infopark Koratty.",
        workStatus="Full-time",
        workMode="Work from office · Infopark Koratty",
        experienceYears="2–3 years",
        requirements=[
            "2 to 3 years experience",
            "Able to work 6:00 pm to 3:00 am shift",
            "Work from office at Infopark, Koratty",
        ],
        responsibilities=["Client marketing coordination as listed by Maple Tech Space"],
        howToApply="Share your resume to careers@mapletechspace.com",
        hiringNotes="Source: Maple Tech Space hiring creative · Sep 2026.",
        description="Client Marketing Coordinator — Maple Tech Space, Infopark Koratty · 2–3 yrs · 6pm–3am · WFO.",
    ),
    job(
        id="cavli-wireless-associate-product-marketing-kochi-sep2026",
        company="Cavli Wireless",
        companyBlurb="Cavli Wireless · Associate – Product Marketing · 0–3 years · Kochi · Full-time",
        location="Kochi, Kerala",
        roles=["Associate – Product Marketing"],
        experience="both",
        experienceRange="0–3 years",
        employmentType="Full-time",
        applyLink="mailto:anmary.joseph@cavliwireless.com?subject=Associate%20-%20Product%20Marketing",
        tags=["Marketing"],
        email="anmary.joseph@cavliwireless.com",
        website="https://www.cavliwireless.com",
        address="Kochi, Kerala",
        industry="IoT / Telecom / Electronics",
        companyDetails="Cavli Wireless builds cellular IoT modules and connected solutions. Hiring Associate – Product Marketing in Kochi.",
        workDetails="Junior Associate – Product Marketing supporting product marketing initiatives for cellular IoT products: positioning, messaging, content, sales enablement, campaigns, and market research. Full-time / permanent. 0–3 years.",
        workStatus="Full-time / Permanent",
        workMode="On-site · Kochi",
        experienceYears="0–3 years",
        skills=["Product marketing", "Content", "IoT", "Sales enablement"],
        requirements=[
            "Bachelor’s degree in Electrical/Electronics Engineering or related field",
            "1–3 years in product marketing preferred (IoT or technology domains)",
            "Foundational knowledge of electronics, integrated circuits, and cellular IoT",
            "Basic understanding of IoT market trends and product lifecycles",
            "Excellent written and verbal communication",
        ],
        responsibilities=[
            "Maintain product knowledge and create marketing content (blogs, white papers, landing pages)",
            "Track product lifecycle stages against roadmap milestones",
            "Support sales with battle cards, case studies, and presentations",
            "Help run go-to-market and multi-channel campaigns",
            "Conduct market research and work with cross-functional teams",
        ],
        howToApply="Send your resume to anmary.joseph@cavliwireless.com",
        hiringNotes="Source: Cavli Wireless hiring creative · Sep 2026.",
        description="Associate – Product Marketing at Cavli Wireless, Kochi · 0–3 years.",
    ),
    job(
        id="cavli-wireless-associate-certification-kochi-sep2026",
        company="Cavli Wireless",
        companyBlurb="Cavli Wireless · Associate – Certification · 0–1 year · Kochi · Female candidates as listed by employer",
        location="Kochi, Kerala",
        roles=["Associate – Certification"],
        experience="fresher",
        experienceRange="0–1 years",
        employmentType="Full-time",
        applyLink="mailto:anmary.joseph@cavliwireless.com?subject=Associate%20-%20Certification",
        tags=["IT", "Business"],
        email="anmary.joseph@cavliwireless.com",
        website="https://www.cavliwireless.com",
        address="Kochi, Kerala",
        industry="IoT / Telecom / Electronics / Semiconductor",
        companyDetails="Cavli Wireless is hiring Associate – Certification in Kochi to support product certification and compliance for cellular IoT modules.",
        workDetails="Full-time / permanent. Coordinate certification with R&D, SCM, labs, and internal teams. Track samples, documents, test schedules, and timelines. Employer creative states strictly female candidates only — confirm eligibility with Cavli.",
        workStatus="Full-time / Permanent",
        workMode="On-site · Kochi",
        experienceYears="0–1 years · fresh graduates welcome",
        skills=["Coordination", "Documentation", "MS Excel", "Compliance"],
        requirements=[
            "0–1 year of experience; fresh graduates welcome",
            "B.Tech in Electronics, Electrical, or Telecommunications Engineering",
            "Good communication, coordination, and analytical skills",
            "MS Excel / Google Sheets, PowerPoint, and documentation tools",
            "Strong organisational and time-management skills",
            "Employer listing states strictly female candidates only — verify with Cavli before applying",
        ],
        responsibilities=[
            "Coordinate product certification activities for cellular IoT modules",
            "Work with R&D, SCM, labs, and internal teams on samples, docs, and schedules",
            "Maintain trackers, timelines, action items, and follow-ups",
            "Support preparation, review, and submission of certification documents",
            "Track testing progress and coordinate closure",
            "Maintain certification reports and certificates in the central repository",
        ],
        howToApply="Send your resume to anmary.joseph@cavliwireless.com",
        hiringNotes="Source: Cavli Wireless hiring creative · Sep 2026. Eligibility as stated by the employer; confirm before applying.",
        description="Associate – Certification at Cavli Wireless, Kochi · 0–1 year.",
    ),
    job(
        id="techvantage-trainee-software-engineer-ai-tvm-sep2026",
        company="techvantage.ai",
        companyBlurb="techvantage.ai · Trainee Software Engineer – AI · Onsite · Trivandrum",
        location="Trivandrum, Kerala",
        roles=["Trainee Software Engineer – AI"],
        experience="fresher",
        experienceRange="Trainee / Fresher",
        employmentType="Full-time",
        applyLink="mailto:jobs@techvantagesystems.com?subject=Trainee%20Software%20Engineer%20-%20AI",
        tags=["IT"],
        email="jobs@techvantagesystems.com",
        website="https://techvantage.ai",
        address="Trivandrum, Kerala",
        industry="AI / Software",
        companyDetails="techvantage.ai (Techvantage Systems) is hiring a Trainee Software Engineer – AI in Trivandrum.",
        workDetails="Onsite trainee software engineer role focused on AI. Trivandrum, Kerala.",
        workStatus="Full-time",
        workMode="Onsite · Trivandrum",
        experienceYears="Trainee",
        skills=["Software engineering", "AI"],
        requirements=["Interest in software engineering and AI", "Able to work onsite in Trivandrum"],
        responsibilities=["Train and contribute as a software engineer on AI-related work as listed by techvantage.ai"],
        howToApply="Send your resume to jobs@techvantagesystems.com. Poster also includes a WhatsApp follow/QR.",
        hiringNotes="Source: techvantage.ai hiring creative · Sep 2026.",
        description="Trainee Software Engineer – AI at techvantage.ai, Trivandrum · onsite.",
    ),
    job(
        id="invoteo-senior-finance-executive-kochi-thiruvalla-sep2026",
        company="Invoteo Future Pvt Ltd",
        companyBlurb="Invoteo · Senior Finance Executive · 3+ years · Thiruvalla & Kochi · ₹2.4–₹3.6 LPA",
        location="Thiruvalla & Kochi, Kerala",
        roles=["Senior Finance Executive"],
        experience="experienced",
        experienceRange="3+ years",
        employmentType="Full-time",
        applyLink="https://wa.me/919778826530",
        tags=["Business"],
        email="",
        phone="+91 97788 26530",
        website="https://www.invoteo.com",
        address="Thiruvalla & Kochi, Kerala",
        industry="Consumer / Comfort products",
        companyDetails="Invoteo Future Pvt Ltd (“simplify living, amplify comfort”) is hiring a Senior Finance Executive for Thiruvalla and Kochi.",
        workDetails="Full-time. 3+ years in Finance / Accounts. CTC ₹2.4–₹3.6 LPA. GST & TDS, accounting & reconciliations, budgeting & cash-flow forecasting, MIS, receivables & payables. Zoho Books & Tally preferred. Immediate joiners preferred.",
        workStatus="Full-time",
        workMode="On-site · Thiruvalla & Kochi",
        experienceYears="3+ years",
        skills=["GST", "TDS", "Accounting", "Tally", "Zoho Books", "MIS"],
        requirements=[
            "3+ years of experience in Finance / Accounts",
            "GST & TDS compliance",
            "Well versed in Zoho Books & Tally preferred",
            "Immediate joiners preferred",
        ],
        responsibilities=[
            "GST & TDS compliance",
            "Accounting and reconciliations",
            "Budgeting and cash-flow forecasting",
            "MIS reporting, receivables and payables",
            "Manage finance for Invoteo",
        ],
        howToApply="Send your resume via WhatsApp to +91 97788 26530",
        hiringNotes="Source: Invoteo hiring creative · Sep 2026. CTC as printed on the poster.",
        description="Senior Finance Executive — Invoteo, Thiruvalla & Kochi · 3+ yrs · ₹2.4–₹3.6 LPA.",
    ),
    job(
        id="boxpush-trainee-supply-chain-kochi-sep2026",
        company="Boxpush India Private Limited",
        companyBlurb="Boxpush · Trainee – Supply Chain · Freshers · Kochi",
        location="Kochi, Kerala",
        roles=["Trainee – Supply Chain"],
        experience="fresher",
        experienceRange="Freshers (0–1 year)",
        employmentType="Full-time",
        applyLink="mailto:lekshmi@stallionindia.com?subject=Trainee%20-%20Supply%20Chain%20-%20Kochi",
        tags=["Business"],
        email="lekshmi@stallionindia.com",
        phone="+91 97460 81320",
        address="Kochi, Kerala",
        industry="Supply chain / Logistics",
        companyDetails="Boxpush India Private Limited is hiring freshers as Trainee – Supply Chain in Kochi.",
        workDetails="Kickstart a career in supply chain operations. Freshers (0–1 year). B.Com / BBA / B.Sc or related graduates preferred.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="0–1 year",
        skills=["Analytical skills", "Problem solving", "Supply chain"],
        requirements=[
            "Freshers (0–1 year of experience)",
            "Good analytical and problem-solving skills",
            "Willingness to learn and grow in supply chain operations",
            "B.Com / BBA / B.Sc (or related) graduates are preferred",
        ],
        responsibilities=["Train in supply chain operations as listed by Boxpush"],
        howToApply="Send your resume to lekshmi@stallionindia.com or call 9746081320",
        hiringNotes="Source: Boxpush hiring creative · Sep 2026.",
        description="Trainee – Supply Chain at Boxpush, Kochi · freshers.",
    ),
    job(
        id="polluxa-cybersecurity-soc-analyst-remote-sep2026",
        company="Polluxa",
        companyBlurb="Polluxa · Cybersecurity / SOC Analyst · Freshers · Remote",
        location="Remote",
        roles=["Cybersecurity / SOC Analyst"],
        experience="fresher",
        experienceRange="Freshers",
        employmentType="Full-time",
        applyLink="mailto:recruitment@polluxa.com?subject=Cybersecurity%20%2F%20SOC%20Analyst",
        tags=["IT"],
        email="recruitment@polluxa.com",
        website="https://www.polluxa.com",
        address="Remote",
        industry="Commerce / Cybersecurity",
        companyDetails="Polluxa (“The future of Commerce, Today”) is hiring a Cybersecurity / SOC Analyst. Freshers. Remote.",
        workDetails="Freshers · Remote. Skills listed: Networking, SIEM, Linux, Log Analysis, Incident Response, Threat Intelligence.",
        workStatus="Full-time",
        workMode="Remote",
        experienceYears="Freshers",
        skills=["Networking", "SIEM", "Linux", "Log analysis", "Incident response", "Threat intelligence"],
        requirements=[
            "Freshers welcome",
            "Networking, SIEM, Linux, log analysis, incident response, and threat intelligence as listed",
        ],
        responsibilities=["SOC / cybersecurity analyst work as listed by Polluxa"],
        howToApply="Submit your resume to recruitment@polluxa.com",
        hiringNotes="Source: Polluxa hiring creative · Sep 2026.",
        description="Cybersecurity / SOC Analyst at Polluxa · freshers · remote.",
    ),
    job(
        id="codeone-full-stack-developer-intern-pune-sep2026",
        company="CodeOne",
        companyBlurb="CodeOne · Full Stack Developer Intern · Fresher · Pune",
        location="Pune",
        roles=["Full Stack Developer Intern"],
        experience="fresher",
        experienceRange="Fresher",
        employmentType="Internship",
        applyLink="mailto:hr@codeone.in?subject=Full%20Stack%20Developer%20Intern",
        tags=["IT"],
        email="hr@codeone.in",
        address="Pune",
        industry="Software",
        companyDetails="CodeOne is hiring a Full Stack Developer Intern in Pune to build responsive websites and web applications.",
        workDetails="Internship · Fresher. HTML, CSS, JavaScript. React.js, Node.js, PHP, or Python is a plus. B.Tech / BCA / B.Sc CS/IT preferred.",
        workStatus="Internship",
        workMode="On-site · Pune",
        experienceYears="Fresher",
        skills=["HTML", "CSS", "JavaScript", "React.js", "Node.js"],
        requirements=[
            "Basic HTML, CSS & JavaScript",
            "React.js, Node.js, PHP, or Python is a plus",
            "Good problem-solving and communication skills",
            "B.Tech / BCA / B.Sc CS/IT preferred — freshers welcome",
        ],
        responsibilities=[
            "Develop and maintain websites/web apps",
            "Write clean, efficient, responsive code",
            "Assist with frontend and backend work",
            "Identify and fix bugs",
        ],
        howToApply="Send your resume to hr@codeone.in",
        hiringNotes="Source: CodeOne hiring creative · Sep 2026.",
        description="Full Stack Developer Intern at CodeOne, Pune · fresher internship.",
    ),
    job(
        id="hotpack-global-accountant-kochi-sep2026",
        company="Hotpack Global",
        companyBlurb="Hotpack Global · Accountant · Kochi · 2+ years UAE experience · Sage 50",
        location="Kochi, Kerala",
        roles=["Accountant"],
        experience="experienced",
        experienceRange="Minimum 2 years UAE experience",
        employmentType="Full-time",
        applyLink="mailto:jobs.gdc@hotpackglobal.com?subject=Accountant%20-%20Kochi",
        tags=["Business"],
        email="jobs.gdc@hotpackglobal.com",
        address="Kochi, Kerala",
        industry="Packaging / Manufacturing",
        companyDetails="Hotpack Global is hiring an Accountant in Kochi.",
        workDetails="Bachelor’s degree. Minimum 2 years UAE experience. Hands-on Sage 50. Bookkeeping, AP/AR, bank reconciliation, invoicing, and financial reporting.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="Minimum 2 years UAE experience",
        skills=["Sage 50", "Bookkeeping", "AP/AR", "Bank reconciliation", "Invoicing"],
        requirements=[
            "Bachelor’s degree",
            "Minimum 2 years UAE experience",
            "Hands-on experience in Sage 50",
            "Bookkeeping, AP/AR and bank reconciliation",
            "Invoicing and financial reporting",
        ],
        responsibilities=["Accounting, AP/AR, bank reconciliation, invoicing, and financial reporting"],
        howToApply="Email jobs.gdc@hotpackglobal.com",
        hiringNotes="Source: Hotpack Global hiring creative · Sep 2026.",
        description="Accountant at Hotpack Global, Kochi · 2 years UAE experience · Sage 50.",
    ),
    job(
        id="lucidplus-management-trainee-business-operations-sep2026",
        company="LucidPlus Infotech Pvt Ltd",
        companyBlurb="LucidPlus Infotech · Management Trainee – Business Operations · Fresh graduates",
        location="Trivandrum, Kerala",
        roles=["Management Trainee – Business Operations"],
        experience="fresher",
        experienceRange="Fresh graduates welcome",
        employmentType="Full-time",
        applyLink="mailto:career@lucidplus.com?subject=Management%20Trainee%20-%20Business%20Operations",
        tags=["Business", "HR"],
        email="career@lucidplus.com",
        address="Trivandrum, Kerala",
        industry="IT Services",
        companyDetails="LucidPlus Infotech Pvt Ltd is hiring a Management Trainee – Business Operations. Fresh graduates welcome.",
        workDetails="Exposure to HR, Finance, Operations & Projects. Communication, analytical and problem-solving skills. MS Office / Google Workspace.",
        workStatus="Full-time",
        workMode="On-site",
        experienceYears="Fresh graduates welcome",
        skills=["MS Office", "Google Workspace", "Communication", "Operations"],
        requirements=[
            "Bachelor’s / Master’s degree",
            "Fresh graduates welcome",
            "Communication, analytical and problem-solving skills",
            "MS Office / Google Workspace",
        ],
        responsibilities=["Support HR, finance, operations, and project work as a management trainee"],
        howToApply="Email career@lucidplus.com",
        hiringNotes="Source: LucidPlus hiring creative · Sep 2026. Location not printed; LucidPlus is a Trivandrum IT company — confirm with HR.",
        description="Management Trainee – Business Operations at LucidPlus Infotech · fresh graduates.",
    ),
    job(
        id="amplitude-qa-trainee-freshers-kollam-sep2026",
        company="Amplitude Software Systems Pvt Ltd",
        companyBlurb="Amplitude Software Systems · QA Trainee · Freshers with testing certification · Kollam",
        location="Kollam, Kerala",
        roles=["QA Trainee"],
        experience="fresher",
        experienceRange="Freshers",
        employmentType="Full-time",
        applyLink="mailto:hr@jupiterbs.com?subject=QA%20Trainee%20-%20Freshers",
        tags=["IT"],
        email="hr@jupiterbs.com",
        address="Kollam, Kerala",
        industry="Software",
        companyDetails="Amplitude Software Systems Pvt Ltd is hiring QA Trainees (freshers) in Kollam, Kerala.",
        workDetails="Software testing certification required. Manual testing – web & mobile applications. Test cases, bug reporting, and retesting. Opportunity to learn automation testing. Apply via hr@jupiterbs.com as printed on the detailed poster.",
        workStatus="Full-time",
        workMode="On-site · Kollam",
        experienceYears="Freshers",
        skills=["Manual testing", "Test cases", "Bug reporting", "Web testing", "Mobile testing"],
        requirements=[
            "Freshers",
            "Software testing certification",
            "Attention to detail, analytical and problem-solving skills",
        ],
        responsibilities=[
            "Manual testing of web and mobile applications",
            "Write test cases, report bugs, and retest",
            "Opportunity to learn automation testing",
        ],
        howToApply="Email hr@jupiterbs.com with subject related to QA Trainee – Freshers",
        hiringNotes="Source: Amplitude Software Systems hiring creatives · Sep 2026. Apply email on the detailed poster is hr@jupiterbs.com.",
        description="QA Trainee (freshers) at Amplitude Software Systems, Kollam · testing certification required.",
    ),
    job(
        id="meckavo-accountant-calicut-sep2026",
        company="Meckavo Sports & Infra",
        companyBlurb="Meckavo Sports & Infra · Accountant · 2+ years Tally & Excel · Calicut",
        location="YMCA Cross Road, Calicut",
        roles=["Accountant"],
        experience="experienced",
        experienceRange="Minimum 2 years Tally and Excel",
        employmentType="Full-time",
        applyLink="https://wa.me/918714615228",
        tags=["Business"],
        email="",
        phone="+91 87146 15228",
        address="YMCA Cross Road, Calicut",
        industry="Sports infrastructure",
        companyDetails="Meckavo Sports & Infra is hiring an Accountant at YMCA Cross Road, Calicut.",
        workDetails="Minimum 2 years Tally and Excel experience.",
        workStatus="Full-time",
        workMode="On-site · Calicut",
        experienceYears="Minimum 2 years",
        skills=["Tally", "Excel"],
        requirements=["Minimum 2 year Tally and Excel experience"],
        responsibilities=["Accounting using Tally and Excel as listed by Meckavo"],
        howToApply="Call or WhatsApp +91 87146 15228",
        hiringNotes="Source: Meckavo hiring creative · Sep 2026.",
        description="Accountant at Meckavo Sports & Infra, Calicut · 2 years Tally & Excel.",
    ),
    job(
        id="penieltech-outbound-sales-executive-remote-sep2026",
        company="Penieltech LLP",
        companyBlurb="Penieltech · Outbound Sales Executive · Remote · UAE market · up to ₹40,000/month + incentives",
        location="Remote (India)",
        roles=["Outbound Sales Executive"],
        experience="both",
        experienceRange="Outbound / telesales experience preferred",
        employmentType="Full-time",
        applyLink="mailto:jobs-tvm@penieltech.com?subject=Outbound%20Sales%20Executive%20-%20Remote",
        tags=["Sales"],
        email="jobs-tvm@penieltech.com",
        address="Based in Trivandrum, Kerala · role is remote across India",
        industry="IT / Sales",
        companyDetails="Penieltech LLP, based in Trivandrum, Kerala, is hiring a remote Outbound Sales Executive targeting UAE customers. Open to candidates anywhere in India.",
        workDetails="Outbound calling and sales. Remote – work from anywhere. Target market: UAE customers. Salary up to INR 40,000/month + attractive incentives. Hindi and English mandatory.",
        workStatus="Full-time",
        workMode="Remote – work from anywhere",
        experienceYears="Outbound calling / telesales preferred",
        skills=["Outbound calling", "Telesales", "Hindi", "English"],
        requirements=[
            "Fluent in Hindi and English — mandatory",
            "Excellent communication and convincing skills",
            "Experience in outbound calling, telesales, or inside sales is preferred",
            "UAE market / customer calling experience is an advantage",
            "Self-motivated, target-oriented, comfortable working independently remotely",
        ],
        responsibilities=[
            "Make outbound calls to customers and prospects in the UAE",
            "Introduce and explain products and services",
            "Generate leads and convert them into sales",
            "Follow up with prospective customers and maintain relationships",
        ],
        howToApply="Send your CV and portfolio to jobs-tvm@penieltech.com",
        hiringNotes="Source: Penieltech hiring creative · Sep 2026. Salary as printed on the poster.",
        description="Remote Outbound Sales Executive at Penieltech · UAE market · up to ₹40,000/month + incentives.",
    ),
    job(
        id="gupio-qa-tester-mysuru-sep2026",
        company="Gupio",
        companyBlurb="Gupio · QA Tester / Software Tester · Mysuru",
        location="Mysuru",
        roles=["QA Tester / Software Tester"],
        experience="both",
        experienceRange="As per company",
        employmentType="Full-time",
        applyLink="mailto:career@mygupio.com?subject=QA%20Tester%20%2F%20Software%20Tester",
        tags=["IT"],
        email="career@mygupio.com",
        website="https://www.mygupio.com",
        address="Mysuru",
        industry="Software / Engineering",
        companyDetails="Gupio (“Engineered For You”) is hiring a QA Tester / Software Tester in Mysuru.",
        workDetails="Work location Mysuru. Send resume to career@mygupio.com. Poster does not list years of experience — confirm with Gupio.",
        workStatus="Full-time",
        workMode="On-site · Mysuru",
        experienceYears="As per company",
        skills=["Software testing", "QA"],
        requirements=["Interest in quality assurance and software testing", "Able to work in Mysuru"],
        responsibilities=["Ensure product quality through software testing as listed by Gupio"],
        howToApply="Send your resume to career@mygupio.com",
        hiringNotes="Source: Gupio hiring creative · Sep 2026.",
        description="QA Tester / Software Tester at Gupio, Mysuru.",
    ),
    job(
        id="uniqz-nagercoil-hiring-sep2026",
        company="Uniqz",
        companyBlurb="Uniqz · Process Associate, Support Analyst, Digital Marketing, Graphic Designer · Nagercoil",
        location="Nagercoil (within 25 km)",
        roles=[
            "Process Associate",
            "Associate Support Analyst",
            "Digital Marketing Executive (Email)",
            "Graphic Designer",
        ],
        experience="both",
        experienceRange="Fresher / Experienced (Graphic Designer 1–2 years)",
        employmentType="Full-time",
        applyLink="mailto:careers@uniqztech.com?subject=Uniqz%20Hiring%20-%20Nagercoil",
        tags=["IT", "Marketing", "Design"],
        email="careers@uniqztech.com",
        phone="+91 88072 40557",
        website="https://www.uniqztech.com",
        address="Nagercoil · within 25 km",
        industry="IT / BPO / Marketing",
        companyDetails="Uniqz is hiring multiple roles in Nagercoil (candidates within 25 km).",
        workDetails="01 Process Associate — Female · 5 positions · Fresher / Experienced. 02 Associate Support Analyst — Female · 5 positions · Fresher / Experienced. 03 Digital Marketing Executive (Email) — Male candidates · 10 positions · Fresher / Experienced. 04 Graphic Designer — 1–2 years · Male & Female. Gender criteria are as printed by the employer — confirm with Uniqz.",
        workStatus="Full-time",
        workMode="On-site · Nagercoil",
        experienceYears="Fresher / Experienced · Graphic Designer 1–2 years",
        skills=["Process operations", "Support", "Email marketing", "Graphic design"],
        requirements=[
            "Location: Nagercoil, within 25 km",
            "Process Associate: 5 positions · fresher/experienced (employer lists female candidates)",
            "Associate Support Analyst: 5 positions · fresher/experienced (employer lists female candidates)",
            "Digital Marketing Executive (Email): 10 positions · fresher/experienced (employer lists male candidates)",
            "Graphic Designer: 1–2 years · male and female candidates",
        ],
        responsibilities=["Role-specific work as listed on the Uniqz hiring creative"],
        howToApply="Share your resume to careers@uniqztech.com or WhatsApp 88072 40557",
        hiringNotes="Source: Uniqz hiring creative · Sep 2026. Role-wise eligibility as printed by the employer.",
        description="Uniqz hiring in Nagercoil — Process Associate, Support Analyst, Digital Marketing, Graphic Designer.",
    ),
    job(
        id="matlab-infotech-developers-qa-surat-sep2026",
        company="MatLab Infotech",
        companyBlurb="MatLab Infotech · Full Stack, MERN Stack, QA Engineer · Surat · Onsite",
        location="Surat",
        roles=["Full Stack Developer", "MERN Stack Developer", "QA Engineer"],
        experience="experienced",
        experienceRange="2.5–4+ years",
        employmentType="Full-time",
        applyLink="mailto:hrjob@matlabinfotech.com?subject=MatLab%20Infotech%20Hiring",
        tags=["IT"],
        email="hrjob@matlabinfotech.com",
        address="Surat",
        industry="IT Services",
        companyDetails="MatLab Infotech is hiring Full Stack, MERN Stack, and QA engineers in Surat (onsite).",
        workDetails="Full Stack Developer — 2.5–3+ years. MERN Stack Developer — 4+ years (grip on BE side). QA Engineer — 3+ years. Qualification B.Tech / B.E. / M.Sc.IT. Onsite Surat.",
        workStatus="Full-time",
        workMode="Onsite · Surat",
        experienceYears="2.5–4+ years",
        skills=["Full stack", "MERN", "Backend", "QA"],
        requirements=[
            "B.Tech / B.E. / M.Sc.IT",
            "Full Stack Developer: 2.5–3+ years",
            "MERN Stack Developer: 4+ years with strong backend",
            "QA Engineer: 3+ years",
            "Onsite in Surat",
        ],
        responsibilities=["Build and test software as listed for each MatLab Infotech role"],
        howToApply="Share your CV at hrjob@matlabinfotech.com",
        hiringNotes="Source: MatLab Infotech hiring creative · Sep 2026.",
        description="MatLab Infotech, Surat — Full Stack (2.5–3+ yrs), MERN (4+ yrs), QA (3+ yrs) · onsite.",
    ),
    job(
        id="flextenure-devops-intern-sep2026",
        company="FlexTenure Solutions Private Limited",
        companyBlurb="FlexTenure · DevOps Intern · Stipend-based · Freshers / students",
        location="India",
        roles=["DevOps Intern"],
        experience="fresher",
        experienceRange="Freshers / students / recent graduates",
        employmentType="Internship",
        applyLink="mailto:pavan.techhead@flextenure.com?subject=Application%20for%20DevOps%20Internship",
        tags=["IT"],
        email="pavan.techhead@flextenure.com",
        industry="IT / DevOps",
        companyDetails="FlexTenure Solutions Private Limited is hiring stipend-based DevOps interns.",
        workDetails="Who can apply: freshers, students, recent graduates, aspiring DevOps engineers. Skills: Linux, Git, Docker, AWS, CI/CD, Bash, Networking.",
        workStatus="Internship",
        workMode="As per company",
        experienceYears="Fresher / student",
        skills=["Linux", "Git", "Docker", "AWS", "CI/CD", "Bash", "Networking"],
        requirements=[
            "Freshers, students, recent graduates, or aspiring DevOps engineers",
            "Linux, Git, Docker, AWS, CI/CD, Bash, Networking as listed",
        ],
        responsibilities=["Hands-on DevOps internship covering Linux, cloud, containers, and CI/CD"],
        howToApply="Send your CV to pavan.techhead@flextenure.com with subject: Application for DevOps Internship – [Your Name]",
        hiringNotes="Source: FlexTenure hiring creative · Sep 2026. Location not printed on the poster.",
        description="Stipend-based DevOps internship at FlexTenure Solutions · freshers and students.",
    ),
    job(
        id="triovate-social-media-graphic-designer-ahmedabad-sep2026",
        company="Triovate",
        companyBlurb="Triovate · Social Media Executive & Graphic Designer · 2–4 years · Ahmedabad",
        location="Science City, Ahmedabad",
        roles=["Social Media Executive", "Graphic Designer"],
        experience="experienced",
        experienceRange="2–4 years",
        employmentType="Full-time",
        applyLink="mailto:hr@triovate.com?subject=Triovate%20Hiring",
        tags=["Marketing", "Design"],
        email="hr@triovate.com",
        website="https://www.triovate.com",
        address="Science City, Ahmedabad",
        industry="Digital / Creative",
        companyDetails="Triovate is hiring a Social Media Executive and a Graphic Designer at Science City, Ahmedabad.",
        workDetails="Social Media Executive: social media management, content creation & scheduling, Meta Ads, international client calls, English communication. Graphic Designer: logo design, social media creatives, branding & visual design, stationery design. Both roles 2–4 years.",
        workStatus="Full-time",
        workMode="On-site · Science City, Ahmedabad",
        experienceYears="2–4 years",
        skills=["Social media", "Meta Ads", "Logo design", "Branding", "English communication"],
        requirements=[
            "2–4 years experience for both roles",
            "Social Media Executive: social management, content, Meta Ads, English, international client calls",
            "Graphic Designer: logos, social creatives, branding, stationery",
        ],
        responsibilities=["Role-specific social media or graphic design work as listed by Triovate"],
        howToApply="Email hr@triovate.com",
        hiringNotes="Source: Triovate hiring creative · Sep 2026.",
        description="Triovate, Ahmedabad — Social Media Executive and Graphic Designer · 2–4 years.",
    ),
    job(
        id="bmw-deutsche-motoren-sales-consultant-north-kerala-sep2026",
        company="BMW Deutsche Motoren",
        companyBlurb="BMW Deutsche Motoren · Sales Consultant · 2–4 years · Kasaragod, Kannur, Wayanad · 6 positions",
        location="Kasaragod · Kannur · Wayanad",
        roles=["Sales Consultant"],
        experience="experienced",
        experienceRange="2–4 years in a similar role",
        employmentType="Full-time",
        applyLink="mailto:ananya.krishnan@bmw-deutschemotoren.in?subject=Sales%20Consultant",
        tags=["Sales"],
        email="ananya.krishnan@bmw-deutschemotoren.in",
        phone="+91 90379 97164",
        address="Kasaragod, Kannur, Wayanad",
        industry="Automotive retail",
        companyDetails="BMW Deutsche Motoren is hiring Sales Consultants for Kasaragod, Kannur, and Wayanad.",
        workDetails="6 positions. 2–4 years in a similar sales role. Drive career in premium automotive retail.",
        workStatus="Full-time",
        workMode="On-site · Kasaragod / Kannur / Wayanad",
        experienceYears="2–4 years",
        skills=["Automotive sales", "Customer consulting"],
        requirements=[
            "2–4 years experience in a similar sales role",
            "Able to work at Kasaragod, Kannur, or Wayanad",
        ],
        responsibilities=["Sales consulting for BMW Deutsche Motoren as listed on the hiring creative"],
        howToApply="Email your resume to ananya.krishnan@bmw-deutschemotoren.in or call 90379 97164",
        hiringNotes="Source: BMW Deutsche Motoren hiring creative · Sep 2026.",
        description="Sales Consultant at BMW Deutsche Motoren — Kasaragod, Kannur, Wayanad · 6 positions · 2–4 yrs.",
    ),
    job(
        id="syamdynamic-triumph-service-technician-kochi-sep2026",
        company="SyamaDynamic",
        companyBlurb="SyamaDynamic (Triumph) · Service Technician (Big Bikes) · Kochi",
        location="Kochi, Kerala",
        roles=["Service Technician (Big Bikes)"],
        experience="experienced",
        experienceRange="Experience servicing premium / big bikes",
        employmentType="Full-time",
        applyLink="mailto:peoplefunction@syamdynamic.com?subject=Service%20Technician%20-%20Big%20Bikes%20-%20Kochi",
        tags=["Business"],
        email="peoplefunction@syamdynamic.com",
        phone="+91 87146 80466",
        address="Kochi, Kerala",
        industry="Automotive / Motorcycle service",
        companyDetails="SyamaDynamic is hiring a Service Technician for Triumph / big bikes in Kochi.",
        workDetails="Experience in servicing premium / big bikes, knowledge of advanced diagnostics and technical systems, passion for motorcycles and customer satisfaction.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="Experience in premium / big bike servicing",
        skills=["Big bike servicing", "Diagnostics", "Customer service"],
        requirements=[
            "Experience in servicing premium / big bikes",
            "Knowledge of advanced diagnostics and technical systems",
            "Passion for motorcycles and customer satisfaction",
        ],
        responsibilities=["Service and diagnose premium / big bikes as listed by SyamaDynamic"],
        howToApply="Send your CV to peoplefunction@syamdynamic.com or call 8714680466",
        hiringNotes="Source: SyamaDynamic / Triumph hiring creative · Sep 2026.",
        description="Service Technician (Big Bikes) at SyamaDynamic, Kochi.",
    ),
    job(
        id="daya-general-hospital-receptionist-thrissur-sep2026",
        company="Daya General Hospital",
        companyBlurb="Daya General Hospital · Receptionist · Front Office · 2+ years · Thrissur",
        location="Thrissur, Kerala",
        roles=["Receptionist"],
        experience="experienced",
        experienceRange="Minimum 2 years",
        employmentType="Full-time",
        applyLink="mailto:hr@dayageneralhospital.com?subject=Receptionist%20-%20Front%20Office",
        tags=["Business"],
        email="hr@dayageneralhospital.com",
        phone="0487 2475114",
        website="https://www.dayageneralhospital.com",
        address="Daya General Hospital, Thrissur",
        industry="Healthcare",
        companyDetails="Daya General Hospital & Speciality Surgical Centre is hiring a Receptionist (Front Office) in Thrissur.",
        workDetails="Any graduation. Front Office. Minimum 2 years experience.",
        workStatus="Full-time",
        workMode="On-site · Thrissur",
        experienceYears="Minimum 2 years",
        skills=["Front office", "Reception"],
        requirements=["Any graduation", "Minimum 2 years experience", "Front office / receptionist background"],
        responsibilities=["Front office reception as listed by Daya General Hospital"],
        howToApply="Send your resume to hr@dayageneralhospital.com or call 0487 2475114",
        hiringNotes="Source: Daya General Hospital hiring creative · Sep 2026.",
        description="Receptionist (Front Office) at Daya General Hospital, Thrissur · 2+ years.",
    ),
    job(
        id="mar-sleeva-family-medicine-physician-palai-sep2026",
        company="Mar Sleeva Medicity Palai",
        companyBlurb="Mar Sleeva Medicity Palai · Family Medicine Physician · DFM/MD/DNB · 0–2 years",
        location="Palai, Kerala",
        roles=["Family Medicine Physician"],
        experience="both",
        experienceRange="0–2 years",
        employmentType="Full-time",
        applyLink="mailto:jobs@marsleevamedicity.com?subject=Family%20Medicine%20Physician",
        tags=["Business"],
        email="jobs@marsleevamedicity.com",
        phone="+91 80752 09662",
        website="https://marsleevamedicity.com",
        address="Mar Sleeva Medicity Palai",
        industry="Healthcare",
        companyDetails="Mar Sleeva Medicity Palai is hiring a Family Medicine Physician.",
        workDetails="Qualification: DFM / MD / DNB in Family Medicine. Experience: 0–2 years.",
        workStatus="Full-time",
        workMode="On-site · Palai",
        experienceYears="0–2 years",
        requirements=["DFM / MD / DNB in Family Medicine", "0–2 years experience"],
        responsibilities=["Family medicine physician duties as listed by Mar Sleeva Medicity Palai"],
        howToApply="Email jobs@marsleevamedicity.com or apply at marsleevamedicity.com. For information: +91 8075209662, +91 9188525970",
        hiringNotes="Source: Mar Sleeva Medicity Palai hiring creative · Sep 2026.",
        description="Family Medicine Physician at Mar Sleeva Medicity Palai · DFM/MD/DNB · 0–2 years.",
    ),
    job(
        id="kadavil-enterprises-tally-billing-staff-vennala-sep2026",
        company="Kadavil Enterprises",
        companyBlurb="Kadavil Enterprises · Tally Billing Staff · Vennala, Ernakulam · ₹20,000–₹30,000+",
        location="Vennala, Ernakulam",
        roles=["Tally Billing Staff"],
        experience="experienced",
        experienceRange="Medium to heavy experience",
        employmentType="Full-time",
        applyLink="https://wa.me/919745380757",
        tags=["Business"],
        email="kadavilhws@gmail.com",
        phone="+91 97453 80757",
        address="47/113/B2, Ground Floor, Fathima Building, Arokkadavu Road, Vennala P.O., Ernakulam",
        industry="Hardware / Trade",
        companyDetails="Kadavil Enterprises (Vennala) is hiring Tally billing staff.",
        workDetails="Working time 9:00 AM to 7:30 PM. Specialist in Tally invoicing and general entry posting. Priority for hardware, paint, power tools, plumbing experience. Medium experience ₹20,000–₹25,000; well experienced ₹30,000+.",
        workStatus="Full-time",
        workMode="On-site · Vennala, Ernakulam",
        experienceYears="Medium to heavy experience",
        skills=["Tally", "Invoicing", "Billing"],
        requirements=[
            "Tally invoicing and general entry posting",
            "Medium or heavy experience",
            "Priority for hardware, paint, power tools, plumbing background",
            "Able to work 9:00 AM to 7:30 PM",
        ],
        responsibilities=["Tally invoicing and general entry posting"],
        howToApply="WhatsApp / DM 9745380757. Also +91 9020212809 or kadavilhws@gmail.com",
        hiringNotes="Source: Kadavil Enterprises hiring creative · Sep 2026. Salary as printed on the poster.",
        description="Tally Billing Staff at Kadavil Enterprises, Vennala · ₹20,000–₹30,000+.",
    ),
    job(
        id="kadavil-enterprises-paint-sales-mixing-vennala-sep2026",
        company="Kadavil Enterprises",
        companyBlurb="Kadavil Enterprises · Paint Sales & Mixing · Vennala · ₹20,000–₹30,000+",
        location="Vennala, Ernakulam",
        roles=["Paint Sales & Mixing Specialist"],
        experience="experienced",
        experienceRange="Medium to well experienced",
        employmentType="Full-time",
        applyLink="https://wa.me/919745380757",
        tags=["Sales"],
        email="kadavilhws@gmail.com",
        phone="+91 97453 80757",
        address="47/113/B2, Ground Floor, Fathima Building, Arokkadavu Road, Vennala P.O., Ernakulam",
        industry="Hardware / Paint retail",
        companyDetails="Kadavil Enterprises (Vennala) is hiring paint sales and mixing staff.",
        workDetails="Working time 8:30 AM to 7:30 PM. Paint mixing and colour matching. Computer proficiency for mixing. Able to lift 20–25 kg (20L paint cans). Customer handling. Prior sales experience is a plus. Medium experience ₹20,000–₹25,000+; well experienced ₹30,000+ per month.",
        workStatus="Full-time",
        workMode="On-site · Vennala, Ernakulam",
        experienceYears="Medium to well experienced",
        skills=["Paint mixing", "Colour matching", "Sales"],
        requirements=[
            "Experience in paint mixing and colour matching",
            "Computer proficiency for mixing",
            "Able to lift 20–25 kg (20L paint cans)",
            "Good with customers",
            "Able to work 8:30 AM to 7:30 PM",
        ],
        responsibilities=["Paint sales, mixing, colour matching, and customer service"],
        howToApply="WhatsApp / DM 9745380757. Also +91 9020212809 or kadavilhws@gmail.com",
        hiringNotes="Source: Kadavil Enterprises hiring creative · Sep 2026. Salary as printed on the poster.",
        description="Paint Sales & Mixing at Kadavil Enterprises, Vennala · ₹20,000–₹30,000+.",
    ),
    job(
        id="swiss-group-showroom-manager-edappally-sep2026",
        company="Swiss Group",
        companyBlurb="Swiss Group · Showroom Manager · Premium furniture · Edappally, Kochi · up to ₹6 LPA",
        location="Edappally, Kochi",
        roles=["Showroom Manager"],
        experience="experienced",
        experienceRange="8–12 years in high-end retail",
        employmentType="Full-time",
        applyLink="mailto:careers@swissgroupindia.com?subject=Showroom%20Manager%20-%20Kochi",
        tags=["Sales", "Business"],
        email="careers@swissgroupindia.com",
        phone="+91 90668 12345",
        address="Edappally, Kochi",
        industry="Premium furniture retail",
        companyDetails="Swiss Group (since 1946) is hiring a Showroom Manager for an upcoming premium furniture showroom in Kochi.",
        workDetails="8–12 years in high-end retail. Any graduate / MBA. Salary up to ₹6 LPA. Mandatory showroom manager experience in luxury or premium retail sales.",
        workStatus="Full-time",
        workMode="On-site · Edappally, Kochi",
        experienceYears="8–12 years",
        skills=["Showroom management", "Retail sales", "Team leadership", "Visual merchandising"],
        requirements=[
            "8–12 years in high-end retail",
            "Mandatory experience as showroom manager in luxury or premium retail sales",
            "Track record in driving sales, store operations, and managing teams",
            "Excellent customer relationship and client servicing",
            "Inventory management and visual merchandising preferred",
            "Any graduate / MBA",
        ],
        responsibilities=[
            "Lead showroom sales and store operations",
            "Manage teams and client relationships",
            "Inventory and visual merchandising as required",
        ],
        howToApply="Email careers@swissgroupindia.com or call +91 9066812345",
        hiringNotes="Source: Swiss Group hiring creative · Sep 2026. CTC as printed on the poster.",
        description="Showroom Manager at Swiss Group premium furniture showroom, Edappally Kochi · 8–12 yrs · up to ₹6 LPA.",
    ),
    job(
        id="peekay-instore-sales-officer-chokli-mahe-sep2026",
        company="Peekay In-Store",
        companyBlurb="Peekay In-Store · Sales Officer · 2–5 years · Chokli, Mahe",
        location="Chokli, Mahe",
        roles=["Sales Officer"],
        experience="experienced",
        experienceRange="2–5 years",
        employmentType="Full-time",
        applyLink="mailto:hrchokli@peekayinstore.com?subject=Sales%20Officer%20-%20Chokli",
        tags=["Sales"],
        email="hrchokli@peekayinstore.com",
        phone="+91 92880 44308",
        address="Chokli, Mahe",
        industry="Tiles & sanitaryware retail",
        companyDetails="Peekay In-Store is hiring a Sales Officer for its tiles and sanitaryware showroom at Chokli, Mahe.",
        workDetails="2 to 5 years in a relevant field. Graduation in any discipline. Good communication skill.",
        workStatus="Full-time",
        workMode="On-site · Chokli, Mahe",
        experienceYears="2–5 years",
        skills=["Retail sales", "Communication"],
        requirements=[
            "2 to 5 years experience in a relevant field",
            "Graduation in any discipline",
            "Good communication skill",
        ],
        responsibilities=["Showroom sales for tiles and sanitaryware as listed by Peekay In-Store"],
        howToApply="Email hrchokli@peekayinstore.com or call +91 92880 44308",
        hiringNotes="Source: Peekay In-Store hiring creative · Sep 2026.",
        description="Sales Officer at Peekay In-Store, Chokli Mahe · 2–5 years.",
    ),
    job(
        id="ufs-technologies-marketing-intern-infopark-kochi-sep2026",
        company="UFS Technologies",
        companyBlurb="UFS Technologies · Marketing Intern · 6 months · Infopark, Kochi",
        location="Infopark, Kochi",
        roles=["Marketing Intern"],
        experience="fresher",
        experienceRange="Internship",
        employmentType="Internship",
        applyLink="mailto:anjana@ufstec.in?subject=Marketing%20Intern%20-%20Infopark%20Kochi",
        tags=["Marketing"],
        email="anjana@ufstec.in",
        phone="+91 98950 85573",
        address="Infopark, Kochi",
        industry="IT / Marketing",
        companyDetails="UFS Technologies is hiring a Marketing Intern at Infopark, Kochi.",
        workDetails="Duration: 6 months. Location: Infopark, Kochi. Opportunity to start a career in marketing.",
        workStatus="Internship",
        workMode="On-site · Infopark, Kochi",
        experienceYears="Internship",
        skills=["Marketing"],
        requirements=["Interest in starting a career in marketing", "Able to intern on-site at Infopark, Kochi for 6 months"],
        responsibilities=["Marketing internship work as listed by UFS Technologies"],
        howToApply="Share your resume to anjana@ufstec.in. Contact +91 9895085573",
        hiringNotes="Source: UFS Technologies hiring creative · Sep 2026.",
        description="Marketing Intern at UFS Technologies, Infopark Kochi · 6 months.",
    ),
    job(
        id="skilme-arabic-translator-hybrid-sep2026",
        company="Skilme",
        companyBlurb="Skilme · Arabic Translator · Hybrid · MA/MSc Psychology or equivalent + Arabic",
        location="Hybrid",
        roles=["Arabic Translator"],
        experience="both",
        experienceRange="As per company",
        employmentType="Full-time",
        applyLink="mailto:hr@skilmeapp.com?subject=Arabic%20Translator",
        tags=["Business"],
        email="hr@skilmeapp.com",
        phone="+91 81119 18707",
        website="https://skilmeapp.com",
        industry="EdTech / Language",
        companyDetails="Skilme is hiring an Arabic Translator. Mode of work: hybrid.",
        workDetails="Requirements as printed: M.A / M.Sc in Psychology or equivalent; proficient in Arabic; excellent translation skills. Hybrid.",
        workStatus="Full-time",
        workMode="Hybrid",
        experienceYears="As per company",
        skills=["Arabic", "Translation"],
        requirements=[
            "M.A / M.Sc in Psychology or equivalent (as printed on the creative)",
            "Proficient in Arabic language",
            "Excellent translation skills",
        ],
        responsibilities=["Arabic translation as listed by Skilme"],
        howToApply="Email hr@skilmeapp.com or WhatsApp 8111918707",
        hiringNotes="Source: Skilme hiring creative · Sep 2026. Qualification as printed on the poster — confirm with Skilme.",
        description="Arabic Translator at Skilme · hybrid.",
    ),
    job(
        id="amala-ims-physician-assistant-thrissur-sep2026",
        company="Amala Institute of Medical Sciences",
        companyBlurb="Amala IMS, Thrissur · Physician Assistant · B.Sc PA · Fresher / Experienced · last date 14 Sep 2026",
        location="Thrissur, Kerala",
        roles=["Physician Assistant"],
        experience="both",
        experienceRange="Fresher / Experienced",
        employmentType="Full-time",
        applyLink="mailto:hrd@amalaims.org?subject=Physician%20Assistant",
        applyDeadline="2026-09-14",
        tags=["Business"],
        email="hrd@amalaims.org",
        phone="0487 2304000",
        website="https://www.amalaims.org",
        address="Amala Nagar P.O, Thrissur, Kerala",
        industry="Healthcare",
        companyDetails="Amala Institute of Medical Sciences, Thrissur is hiring a Physician Assistant.",
        workDetails="Qualification: B.Sc Physician Assistant. Experience: Fresher / Experienced. Printed last date: on or before 14-09-2026 — confirm with AIMS if still open.",
        workStatus="Full-time",
        workMode="On-site · Thrissur",
        experienceYears="Fresher / Experienced",
        requirements=["B.Sc Physician Assistant", "Fresher or experienced"],
        responsibilities=["Physician assistant duties as listed by Amala IMS"],
        howToApply="Send CV to hrd@amalaims.org",
        hiringNotes="Source: Amala IMS hiring creative · Sep 2026. Printed last date 14 Sep 2026 — verify with HRD before applying.",
        description="Physician Assistant at Amala IMS, Thrissur · B.Sc PA · last date printed 14 Sep 2026.",
    ),
    job(
        id="jays-academy-aptitude-trainers-tvm-sep2026",
        company="Jay's Academy",
        companyBlurb="Jay's Academy · Aptitude Trainers (CAT/GRE/GMAT) & Placement Training · Pattom, TVM",
        location="Pattom, Thiruvananthapuram",
        roles=["Aptitude Trainer", "Soft Skills Trainer", "Technical Trainer", "Placement Training"],
        experience="both",
        experienceRange="Teaching experience preferred",
        employmentType="Full-time",
        applyLink="mailto:careers@jaysacademy.in?subject=Aptitude%20Trainer%20/%20Placement%20Training",
        tags=["Business"],
        email="careers@jaysacademy.in",
        phone="+91 90619 91932",
        address="First Floor, Kailas Plaza, Pattom Jn, Thiruvananthapuram - 04",
        industry="Education / Test prep",
        companyDetails="Jay's Academy (Pattom, Thiruvananthapuram) is hiring aptitude trainers for CAT, GRE, and GMAT, plus placement training (aptitude, soft skills, technical).",
        workDetails="Strong quantitative aptitude and logical reasoning. Ability to explain concepts and engage students. Prior CAT/GRE/GMAT teaching preferred. Placement training experience is an added advantage.",
        workStatus="Full-time",
        workMode="On-site · Pattom, Thiruvananthapuram",
        experienceYears="Teaching experience preferred",
        skills=["Quantitative aptitude", "Logical reasoning", "CAT", "GRE", "GMAT", "Training"],
        requirements=[
            "Strong command over quantitative aptitude and logical reasoning",
            "Ability to explain concepts clearly and engage with students",
            "Prior experience teaching CAT / GRE / GMAT preferred, not mandatory",
            "Passion for teaching and mentoring",
            "Placement training experience is an added advantage",
        ],
        responsibilities=["Train aspirants for CAT, GRE, GMAT and/or placement aptitude, soft skills, or technical modules"],
        howToApply="Email resume and cover letter to careers@jaysacademy.in. Enquiries: 9061991932, 8893390001",
        hiringNotes="Source: Jay's Academy hiring creative · Sep 2026.",
        description="Aptitude / placement trainers at Jay's Academy, Pattom TVM — CAT, GRE, GMAT.",
    ),
    job(
        id="icici-prudential-financial-advisors-sep2026",
        company="ICICI Prudential Life Insurance",
        companyBlurb="ICICI Prudential · Financial Advisors · Commission-based · flexible timing",
        location="Kerala",
        roles=["Financial Advisor"],
        experience="both",
        experienceRange="As per company",
        employmentType="Contract",
        applyLink="https://wa.me/918891289128",
        tags=["Sales", "Business"],
        phone="+91 88912 89128",
        industry="Life insurance",
        companyDetails="ICICI Prudential Life Insurance is hiring Financial Advisors (commission-based opportunity as printed).",
        workDetails="Flexible timing. Commission-based income. Training and support. Network-based advisory as printed on the creative — confirm engagement type with the recruiter.",
        workStatus="Commission-based as printed",
        workMode="Flexible",
        experienceYears="As per company",
        skills=["Sales", "Financial advisory"],
        requirements=["Willingness to build a financial advisory practice as listed"],
        responsibilities=["Advise customers on life insurance / financial security as listed by ICICI Prudential"],
        howToApply="Call or WhatsApp 8891289128",
        hiringNotes="Source: ICICI Prudential hiring creative · Sep 2026. Commission-based; verify terms before committing.",
        description="Financial Advisors at ICICI Prudential Life Insurance · commission-based · WhatsApp 8891289128.",
    ),
    job(
        id="easy-store-branch-accountant-edappally-walkin-sep12-2026",
        company="Easy Store",
        companyBlurb="Easy Store · Branch Accountant · B.Com fresher · Walk-in 12 Sep 2026 · Edappally (male candidates as listed)",
        location="Edappally, Ernakulam",
        roles=["Branch Accountant"],
        experience="fresher",
        experienceRange="B.Com fresher",
        employmentType="Full-time",
        applyLink="mailto:KERALA.HR@EASYSTOREMEA.COM?subject=Branch%20Accountant%20-%20B.Com%20Fresher",
        applyDeadline="2026-09-12",
        tags=["Business"],
        isWalkIn=True,
        walkInDate="12 September 2026 · 10:30 AM (printed date — confirm if still open)",
        email="KERALA.HR@EASYSTOREMEA.COM",
        phone="+91 86066 00068",
        address="Easy Store Head Office, 2nd Floor, SK Tower, Near Lulu Mall, Edappally, Ernakulam, Kerala 682024",
        industry="Retail",
        companyDetails="Easy Store is hiring Branch Accountants (B.Com freshers) with vacancies across Kerala. Walk-in listed at Edappally head office.",
        workDetails="B.Com fresher. Salary as per company standards. ESI & PF; accommodation only. Walk-in Saturday 12-09-2026, 10:30 AM. Creative states male candidates only — confirm with HR. Vacancies across Kerala.",
        workStatus="Full-time",
        workMode="On-site · vacancies across Kerala / walk-in at Edappally",
        experienceYears="Fresher",
        skills=["Accounting", "B.Com"],
        requirements=[
            "B.Com (fresher)",
            "Walk-in as printed: 12 Sep 2026, 10:30 AM at Edappally HO",
            "Employer listing states male candidates only — verify with Easy Store",
        ],
        responsibilities=["Branch accounting as listed by Easy Store"],
        howToApply="Walk-in at Easy Store Head Office, 2nd Floor, SK Tower, near Lulu Mall, Edappally — or call 8606600068 / email KERALA.HR@EASYSTOREMEA.COM. Printed walk-in date is 12 Sep 2026; confirm before travelling.",
        hiringNotes="Source: Easy Store hiring creative · Sep 2026. Printed walk-in 12 Sep 2026 may have passed — email or call first.",
        description="Branch Accountant (B.Com fresher) at Easy Store — walk-in Edappally as printed 12 Sep 2026.",
    ),
    job(
        id="kunnamkulam-jewellery-graphic-designer-sep2026",
        company="Jewellery industry (Kunnamkulam)",
        companyBlurb="Jewellery industry · Graphic Designer · 2–4 years · Kunnamkulam, Thrissur",
        location="Kunnamkulam, Thrissur",
        roles=["Graphic Designer"],
        experience="experienced",
        experienceRange="2–4 years",
        employmentType="Full-time",
        applyLink="https://wa.me/919895260884",
        tags=["Design"],
        phone="+91 98952 60884",
        address="Kunnamkulam, Thrissur",
        industry="Jewellery",
        companyDetails="A jewellery industry employer in Kunnamkulam, Thrissur is hiring a Graphic Designer (company name not printed on the creative).",
        workDetails="Education: B.Sc / BCA / Diploma. 2 to 4 years. Create graphics for social, print, and digital; posters, banners, brochures, presentations. Salary as per experience.",
        workStatus="Full-time",
        workMode="On-site · Kunnamkulam, Thrissur",
        experienceYears="2–4 years",
        skills=["Graphic design", "Social media creatives", "Print design"],
        requirements=[
            "B.Sc / BCA / Diploma",
            "2 to 4 years experience",
            "Passion for design and creativity",
        ],
        responsibilities=[
            "Create graphics for social media, print, and digital platforms",
            "Design posters, banners, brochures, and presentations",
            "Work with the team on project requirements",
        ],
        howToApply="WhatsApp your CV to 9895260884",
        hiringNotes="Source: jewellery hiring creative · Sep 2026. Company name not printed — confirm identity before sharing documents.",
        description="Graphic Designer for a jewellery employer in Kunnamkulam, Thrissur · 2–4 years.",
    ),
    job(
        id="pvs-sunrise-billing-associate-cafeteria-kozhikode-sep2026",
        company="PVS Sunrise Hospital",
        companyBlurb="PVS Sunrise Hospital · Billing Associate – Cafeteria · 0–2 years · Kozhikode",
        location="Kozhikode, Kerala",
        roles=["Billing Associate – Cafeteria"],
        experience="both",
        experienceRange="Freshers / 0–2 years",
        employmentType="Full-time",
        applyLink="mailto:hr@pvssunrise.com?subject=Billing%20Associate%20-%20Cafeteria",
        tags=["Business"],
        email="hr@pvssunrise.com",
        phone="+91 97786 89171",
        address="P V Gangadharan Road, Kozhikode",
        industry="Healthcare",
        companyDetails="PVS Sunrise Hospital, Kozhikode is hiring a Billing Associate for the cafeteria.",
        workDetails="Bachelor’s degree in a relevant field. Freshers / 0 to 2 years in a similar role preferred. Billing & invoicing, cafeteria operations assistance, customer service, record keeping.",
        workStatus="Full-time",
        workMode="On-site · Kozhikode",
        experienceYears="0–2 years",
        skills=["Billing", "Invoicing", "Customer service"],
        requirements=[
            "Bachelor’s degree (relevant field)",
            "Freshers / 0 to 2 years in a similar role preferred",
        ],
        responsibilities=[
            "Billing and invoicing support",
            "Cafeteria operations assistance",
            "Customer service",
            "Record keeping and documentation",
        ],
        howToApply="Email hr@pvssunrise.com or call 9778689171 / 0495 270 7270",
        hiringNotes="Source: PVS Sunrise Hospital hiring creative · Sep 2026.",
        description="Billing Associate – Cafeteria at PVS Sunrise Hospital, Kozhikode · 0–2 years.",
    ),
    job(
        id="arjuna-natural-plant-roles-aluva-sep2026",
        company="Arjuna Natural",
        companyBlurb="Arjuna Natural · Plant Operator, Graduate Apprentice, Helper · Aluva",
        location="Aluva, Kerala",
        roles=["Plant Operator", "Graduate Apprentice Trainee", "Helper – Plant Operations"],
        experience="both",
        experienceRange="0–8 years depending on role",
        employmentType="Full-time",
        applyLink="mailto:anand.k@arjunanatural.com?subject=Arjuna%20Natural%20Plant%20Hiring%20-%20Aluva",
        tags=["Business"],
        email="anand.k@arjunanatural.com",
        phone="+91 73562 37555",
        address="Aluva, Kerala",
        industry="Nutraceutical manufacturing",
        companyDetails="Arjuna Natural is hiring plant-side roles in Aluva.",
        workDetails="Plant Operator: any ITI / diploma, 2–8 years, male as printed. Graduate Apprentice Trainee: ITI / diploma / M.Sc Microbiology, 24-month apprenticeship, male as printed. Helper – Plant Operations: SSLC, Plus Two & above, 0–5 years, female only (prefer local) as printed. Gender criteria as listed by the employer — confirm with Arjuna.",
        workStatus="Full-time / Apprenticeship",
        workMode="On-site · Aluva",
        experienceYears="0–8 years depending on role",
        skills=["Plant operations", "Manufacturing"],
        requirements=[
            "Plant Operator: any ITI / diploma · 2–8 years (employer lists male)",
            "Graduate Apprentice Trainee: ITI / diploma / M.Sc Microbiology · 24 months (employer lists male)",
            "Helper – Plant Operations: SSLC / Plus Two & above · 0–5 years (employer lists female; prefer local)",
        ],
        responsibilities=["Plant operations, apprenticeship, or helper duties as listed for each role"],
        howToApply="Email anand.k@arjunanatural.com or call 7356237555",
        hiringNotes="Source: Arjuna Natural hiring creative · Sep 2026. Role-wise eligibility as printed by the employer.",
        description="Arjuna Natural, Aluva — Plant Operator, Graduate Apprentice, Helper – Plant Operations.",
    ),
    job(
        id="90plus-sales-manager-team-leader-infopark-thrissur-sep2026",
        company="90+ My Tuition App",
        companyBlurb="90+ My Tuition App · Sales Manager / Team Leader · EdTech · 3–8 years · Infopark Thrissur",
        location="Infopark, Thrissur",
        roles=["Sales Manager / Team Leader"],
        experience="experienced",
        experienceRange="3–8 years",
        employmentType="Full-time",
        applyLink="mailto:smhr@90plus.in?subject=Sales%20Manager%20/%20Team%20Leader",
        tags=["Sales"],
        email="smhr@90plus.in",
        website="https://www.mytuitionapp.com",
        address="Infopark, Thrissur",
        industry="EdTech",
        companyDetails="90+ My Tuition App is hiring a Sales Manager / Team Leader at Infopark Thrissur. EdTech experience mandatory.",
        workDetails="Any degree / PG. Location Infopark Thrissur. Experience 3–8 years. EdTech experience mandatory.",
        workStatus="Full-time",
        workMode="On-site · Infopark Thrissur",
        experienceYears="3–8 years",
        skills=["Sales management", "Team leadership", "EdTech sales"],
        requirements=[
            "Any degree / PG",
            "3–8 years experience",
            "EdTech experience mandatory",
            "Able to work at Infopark, Thrissur",
        ],
        responsibilities=["Lead sales / team as listed by 90+ My Tuition App"],
        howToApply="Send your resume to smhr@90plus.in",
        hiringNotes="Source: 90+ My Tuition App hiring creative · Sep 2026.",
        description="Sales Manager / Team Leader at 90+ My Tuition App, Infopark Thrissur · 3–8 yrs · EdTech mandatory.",
    ),
    job(
        id="malankara-credit-society-gold-loan-officer-thoppumpady-sep2026",
        company="Malankara Credit Society Ltd (MCS Ltd)",
        companyBlurb="MCS Ltd · Gold Loan Officer · Thoppumpady · freshers can apply",
        location="Thoppumpady, Kochi",
        roles=["Gold Loan Officer"],
        experience="both",
        experienceRange="Gold loan experience preferred · freshers can apply",
        employmentType="Full-time",
        applyLink="mailto:hr2@mmsccs.com?subject=Gold%20Loan%20Officer%20-%20Thoppumpady",
        tags=["Business"],
        email="hr2@mmsccs.com",
        phone="+91 99473 86909",
        address="Thoppumpady",
        industry="Credit society / BFSI",
        companyDetails="Malankara Credit Society Ltd (MCS Ltd) is hiring a Gold Loan Officer at Thoppumpady.",
        workDetails="Experience in gold loan. Attractive salary, incentives, EPF and other statutory benefits. Freshers (male or female) can apply.",
        workStatus="Full-time",
        workMode="On-site · Thoppumpady",
        experienceYears="Gold loan experience preferred · freshers welcome",
        skills=["Gold loan", "Customer service"],
        requirements=["Experience in gold loan preferred", "Freshers can apply"],
        responsibilities=["Gold loan officer duties as listed by MCS Ltd"],
        howToApply="Submit resume to hr2@mmsccs.com or 9947386909",
        hiringNotes="Source: MCS Ltd / Malankara Credit Society hiring creative · Sep 2026.",
        description="Gold Loan Officer at Malankara Credit Society, Thoppumpady · freshers can apply.",
    ),
    job(
        id="ident-vfx-jr-production-coordinator-kochi-sep2026",
        company="Ident VFX Lab",
        companyBlurb="Ident VFX Lab · Jr. Production Coordinator – VFX · 1–2 years · Kochi on-site",
        location="Kochi, Kerala",
        roles=["Jr. Production Coordinator – VFX"],
        experience="experienced",
        experienceRange="1–2 years",
        employmentType="Full-time",
        applyLink="mailto:career.identvfxlab@gmail.com?subject=Jr.%20Production%20Coordinator%20-%20VFX",
        tags=["Design", "Business"],
        email="career.identvfxlab@gmail.com",
        address="Kochi · On-site",
        industry="VFX / Production",
        companyDetails="Ident VFX Lab is hiring a Junior Production Coordinator with 1–2 years of experience to coordinate across artists, supervisors, and production teams.",
        workDetails="Full-time · Kochi on-site · immediate joining. Coordination, documentation, spreadsheets, VFX pipeline awareness.",
        workStatus="Full-time",
        workMode="On-site · Kochi",
        experienceYears="1–2 years",
        skills=["Production coordination", "Documentation", "Spreadsheets", "VFX pipeline"],
        requirements=[
            "1–2 years experience",
            "Strong coordination, follow-up, documentation, and organisation",
            "Good written and verbal communication",
            "Ability to track shots, priorities, review notes, and delivery status",
            "Basic understanding of the VFX pipeline and departmental workflow",
            "Comfortable with spreadsheets, production trackers, and documentation",
            "Immediate joining preferred",
        ],
        responsibilities=[
            "Coordinate across artists, supervisors, and production teams",
            "Track shots, reviews, and deliveries",
            "Maintain accurate production information under deadlines",
        ],
        howToApply="Apply with your CV to career.identvfxlab@gmail.com",
        hiringNotes="Source: Ident VFX Lab hiring creative · Sep 2026.",
        description="Jr. Production Coordinator – VFX at Ident VFX Lab, Kochi · 1–2 years · on-site · immediate.",
    ),
    job(
        id="sai-service-admin-executive-kayamkulam-chengannur-sep2026",
        company="Sai Service (Maruti Suzuki)",
        companyBlurb="Sai Service · Admin Executive · 1+ year · Kayamkulam and Chengannur",
        location="Kayamkulam and Chengannur",
        roles=["Admin Executive"],
        experience="experienced",
        experienceRange="Minimum 1 year",
        employmentType="Full-time",
        applyLink="mailto:hrchengannur@saiservice.com?subject=Admin%20Executive",
        tags=["Business"],
        email="hrchengannur@saiservice.com",
        phone="+91 92880 32892",
        address="Kayamkulam and Chengannur",
        industry="Automotive after-sales",
        companyDetails="Sai Service (Maruti Suzuki dealer) is hiring an Admin Executive for Kayamkulam and Chengannur.",
        workDetails="Degree. Minimum 1 year experience. ESI & PF benefits. Yearly increment.",
        workStatus="Full-time",
        workMode="On-site · Kayamkulam and Chengannur",
        experienceYears="Minimum 1 year",
        skills=["Administration"],
        requirements=["Degree", "Minimum 1 year experience"],
        responsibilities=["Admin executive work as listed by Sai Service"],
        howToApply="Email hrchengannur@saiservice.com or call 9288032892 / 9288024207",
        hiringNotes="Source: Sai Service hiring creative · Sep 2026.",
        description="Admin Executive at Sai Service (Maruti Suzuki) — Kayamkulam and Chengannur · 1+ year.",
    ),
    job(
        id="meeran-legal-intern-edappally-sep2026",
        company="Meeran",
        companyBlurb="Meeran · Legal Intern (Admin Support) · Paid internship · Edappally · female degree holder as listed",
        location="Edappally, Kochi",
        roles=["Legal Intern – Admin Support"],
        experience="fresher",
        experienceRange="Degree holder",
        employmentType="Internship",
        applyLink="mailto:career@groupmeeran.com?subject=Legal%20Intern%20-%20Admin%20Support",
        tags=["Business"],
        email="career@groupmeeran.com",
        phone="+91 75940 55518",
        address="Edappally",
        industry="Legal",
        companyDetails="Meeran is hiring a paid Legal Intern (Admin Support) in Edappally.",
        workDetails="Paid internship. Qualification: degree holder. Preference: female candidate as printed. Location: Edappally.",
        workStatus="Paid internship",
        workMode="On-site · Edappally",
        experienceYears="Internship",
        skills=["Legal admin", "Documentation"],
        requirements=[
            "Degree holder",
            "Employer listing prefers a female candidate — confirm with Meeran",
        ],
        responsibilities=["Legal department admin support as listed by Meeran"],
        howToApply="Email career@groupmeeran.com or WhatsApp 7594055518",
        hiringNotes="Source: Meeran hiring creative · Sep 2026. Eligibility as printed by the employer.",
        description="Paid Legal Intern (Admin Support) at Meeran, Edappally.",
    ),
    job(
        id="sunrise-hospitals-referral-marketing-kerala-sep2026",
        company="Sunrise Hospitals",
        companyBlurb="Sunrise Hospitals · Referral Marketing (Executive to Senior Manager) · 2–12+ years · Kerala units",
        location="Kochi · Calicut · Erattupetta · Kanhangad · Changaramkulam · Kulanada",
        roles=[
            "Referral Marketing Executive",
            "Referral Marketing Assistant Manager",
            "Referral Marketing Manager",
            "Referral Marketing Senior Manager",
        ],
        experience="experienced",
        experienceRange="2–12+ years based on position",
        employmentType="Full-time",
        applyLink="mailto:corporatehr@sunrisehospital.in?subject=Referral%20Marketing",
        tags=["Marketing", "Sales"],
        email="corporatehr@sunrisehospital.in",
        phone="+91 70342 58885",
        website="https://www.sunrisehospital.in",
        industry="Healthcare",
        companyDetails="Sunrise Hospitals is hiring Referral Marketing roles from Executive to Senior Manager across hospital units in Kerala.",
        workDetails="Qualification: B.Com / M.Com / MBA. Experience: 2–12+ years based on position. Units: Kochi, Calicut, Erattupetta, Kanhangad, Changaramkulam, Kulanada.",
        workStatus="Full-time",
        workMode="On-site · across Sunrise Hospital units",
        experienceYears="2–12+ years",
        skills=["Referral marketing", "Healthcare marketing"],
        requirements=[
            "B.Com / M.Com / MBA",
            "2–12+ years depending on the position",
        ],
        responsibilities=["Referral marketing as listed for Executive / AM / Manager / Senior Manager"],
        howToApply="Email corporatehr@sunrisehospital.in or call 7034258885",
        hiringNotes="Source: Sunrise Hospitals hiring creative · Sep 2026.",
        description="Referral Marketing (Executive to Senior Manager) at Sunrise Hospitals across Kerala units.",
    ),
    job(
        id="smt-labs-android-developer-sep2026",
        company="SMT Labs",
        companyBlurb="SMT Labs · Android Developer · 2–4 years · Kotlin, Jetpack Compose, Firebase",
        location="As per company",
        roles=["Android Developer"],
        experience="experienced",
        experienceRange="2–4 years",
        employmentType="Full-time",
        applyLink="mailto:hr@smtlabs.io?subject=Android%20Developer",
        tags=["IT"],
        email="hr@smtlabs.io",
        website="https://smtlabs.io",
        industry="Technology / Engineering",
        companyDetails="SMT Labs (“Your trusted Technology and engineering partner”) is hiring an Android Developer.",
        workDetails="2–4 years. Design, develop and maintain Android apps; REST APIs and third-party libraries; modern Android and Jetpack components; performance, quality, and responsiveness. Stack: Kotlin, Jetpack Compose, Firebase, Retrofit, Material Design. Location not printed on the creative — confirm with SMT Labs.",
        workStatus="Full-time",
        workMode="As per company",
        experienceYears="2–4 years",
        skills=["Kotlin", "Jetpack Compose", "Firebase", "Retrofit", "Material Design", "REST APIs", "MVVM"],
        requirements=[
            "2–4 years Android development experience",
            "Kotlin, Jetpack Compose, MVVM, REST APIs",
            "Firebase, Retrofit, Material Design as listed",
        ],
        responsibilities=[
            "Design, develop and maintain high-quality Android applications",
            "Integrate RESTful APIs and third-party libraries",
            "Work with modern Android technologies and Jetpack components",
            "Ensure performance, quality, and responsiveness",
            "Collaborate with cross-functional teams",
            "Discover, evaluate, and implement new technologies",
        ],
        howToApply="Send your CV to ayushi.malviya@smtlabs.io or hr@smtlabs.io",
        hiringNotes="Source: SMT Labs hiring creative · Sep 2026. Location not printed — confirm with HR before applying.",
        description="Android Developer at SMT Labs · 2–4 years · Kotlin, Jetpack Compose, Firebase, Retrofit.",
    ),
]


def main() -> None:
    n = mod.insert_jobs(ROOT / "data" / "jobs-data.js", "JOBS", JOBS)
    print(f"Added {n} WhatsApp jobs to jobs-data.js")


if __name__ == "__main__":
    main()
