"""Render the static company page: python3 scripts/build-enitexa.py."""
import json
from pathlib import Path
from html import escape as e
ROOT=Path(__file__).resolve().parents[1]
d=json.loads((ROOT/'data/enitexa/content.json').read_text())
def link(url,label,cls=''):
 return f'<a class="{cls}" href="{e(url)}"'+(' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else '')+f'>{label}</a>'
def heading(n,title,desc=''):
 return f'<div class="section-head"><p class="eyebrow">{n}</p><div><h2>{title}</h2>'+(f'<p>{desc}</p>' if desc else '')+'</div></div>'
def visual(p):
 return f'<div class="project-visual">'+(f'<img src="/assets/enitexa/{p["image"]}" alt="{e(p["name"])} website capture" loading="lazy" width="1440" height="1000">' if p.get('image') else f'<span class="project-monogram" aria-hidden="true">{e(p["mark"])}</span><small>Typographic illustration · screenshot unavailable</small>')+'</div>'
nav=''.join(link('#'+id,label) for id,label in [('overview','Overview'),('solutions','Solutions'),('work','Work'),('about','About'),('process','Process'),('contact','Contact')])
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enitexa.ai — Software, Design & Digital Solutions | Kochi</title><meta name="description" content="Meet Enitexa.ai: your technology and creative partner in Kochi. Explore our leadership, mobile apps, websites, ERP, design, selected work, and digital support."><link rel="canonical" href="https://infoparkdaily.online/software-solutions/"><meta name="theme-color" content="#f4f3ed"><meta property="og:type" content="website"><meta property="og:title" content="Enitexa.ai — Ideas into everyday impact"><meta property="og:description" content="Software, design, and digital support. One coordinated team in Kochi, from product planning through launch."><meta property="og:url" content="https://infoparkdaily.online/software-solutions/"><meta property="og:image" content="https://infoparkdaily.online/assets/enitexa/social-preview.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;600;700&family=Manrope:wght@400;500;600;650;700;750;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/css/software-solutions.css?v=20260912"><script defer src="/js/software-solutions.js?v=20260912"></script></head><body class="en-page"><a class="en-skip" href="#main">Skip to content</a>'''
html+=f'<div class="parent-bar"><div class="wrap">{link("/","← An InfoparkDaily technology partner")}<span>KAKKANAD, KOCHI · INDIA</span></div></div><header class="en-header"><div class="wrap header-inner"><a class="wordmark" href="/software-solutions/" aria-label="Enitexa.ai home"><span class="brand-symbol" aria-hidden="true">✳</span> enitexa<span>.ai</span></a><nav id="en-nav" aria-label="Main navigation">{nav}</nav>{link("#contact","Let’s talk ↗","button header-cta")}<button class="en-menu-toggle" aria-controls="en-nav" aria-expanded="false" aria-label="Open navigation menu">Menu <span>＋</span></button></div></header>'
html+='''<main id="main"><section class="hero wrap" id="overview"><div class="hero-top"><p class="eyebrow"><span class="status-dot"></span> YOUR EXTENDED TECHNOLOGY & CREATIVE TEAM</p><span class="hero-note">STRATEGY → DESIGN → ENGINEERING</span></div><h1>From business idea<br>to the systems behind<br><span>your growth.</span><span class="hero-asterisk" aria-hidden="true">✳</span></h1><div class="hero-bottom"><p>We bring product strategy, mobile and web development, business software, design, and digital support together—helping you build, launch, and improve with one accountable partner.</p><div class="hero-actions"><a class="button" href="#contact">Start a Project <span aria-hidden="true">↗</span></a><a class="text-link" href="#work">Explore Our Work <span aria-hidden="true">↓</span></a></div></div><div class="hero-showcase"><div class="showcase-caption"><span><span class="status-dot"></span> BUILT FOR THE EVERYDAY</span><span>01 / INFOPARKDAILY</span></div><div class="desktop-frame"><div class="browser-bar"><span>● ● ●</span><span>infoparkdaily.online</span><span>↗</span></div><img src="/assets/enitexa/infopark-desktop.webp" alt="Actual InfoparkDaily homepage, desktop view" width="1440" height="1000" fetchpriority="high"></div><div class="mobile-frame"><img src="/assets/enitexa/infopark-mobile.webp" alt="Actual InfoparkDaily homepage, mobile view" width="390" height="800"></div><div class="showcase-side"><span>ONE PLATFORM.<br>A CONNECTED<br>COMMUNITY.</span><span class="giant-arrow" aria-hidden="true">↗</span></div><span class="capture-label">Actual project captures · Desktop + mobile</span></div><div class="capability-strip"><span>Mobile applications</span><span>Web platforms</span><span>Business systems</span><span>Design & creative</span><span>Digital growth</span></div></section>'''
html+='<section class="wrap section selected">'+heading('01 / SELECTED WORK','A few things we’ve<br>helped bring to life.')+'<div class="preview-grid">'
for i in [0,1,3]:
 p=d['projects'][i];html+=f'<a class="preview" href="#project-{i}">{visual(p)}<div class="project-meta"><span>{p["category"]}</span><span aria-hidden="true">↗</span></div><h3>{p["name"]}</h3></a>'
html+='</div></section><section class="about-band" id="about"><div class="wrap section">'+heading('02 / WHO WE ARE','Technology expertise.<br>Creative thinking.<br><span class="muted">Clear ownership.</span>')+'''<div class="about-body"><div class="location-stamp"><span aria-hidden="true">↗</span><p>Rooted in Kochi.<br>Built around your business.</p></div><div><p class="large-copy">Enitexa.ai is a software and digital solutions partner helping founders, businesses, and growing teams turn practical needs into useful digital products.</p><p>We bring together strategy, design, engineering, and ongoing support across mobile applications, web platforms, business systems, and brand experiences. From defining a first release to improving an existing platform, we organize work around clear scope, visible milestones, and consistent communication.</p><p>Based in Kakkanad, Kochi, we support startups, established businesses, agencies, and operational teams through focused projects, specialist improvements, and ongoing partnerships.</p><div class="mission-grid"><div><h3>Our mission</h3><p>Turn business needs into dependable digital products through thoughtful design, disciplined engineering, and clear communication.</p></div><div><h3>Our vision</h3><p>Become a trusted long-term technology and creative partner for businesses building their next stage of growth.</p></div></div></div></div></div></section>'''
html+='<section class="wrap section" id="solutions">'+heading('03 / OUR SOLUTIONS','One team.<br>A wider perspective.','Bring us a specific challenge, or bring the whole product. Explore the capabilities we can bring together.')+'<div class="service-catalogue">'
for i,(name,desc,audience,services) in enumerate(d['services']):
 html+=f'<details class="service-group"'+(' open' if i==0 else '')+f'><summary><span class="row-index">0{i+1}</span><span><strong>{name}</strong><small>{desc}</small></span><span class="plus" aria-hidden="true">＋</span></summary><div class="service-body"><p class="service-audience">For {audience[0].lower()+audience[1:]}</p><div class="service-list">'
 for title,deliver,benefit in services:
  html+=f'<details class="service-item"><summary>{e(title)}<span aria-hidden="true">+</span></summary><div><p><b>We can deliver:</b> {e(deliver)}</p><p><b>For your business:</b> {e(benefit)}</p><a class="text-link" href="#contact" data-service="{e(title)}">Discuss this service ↗</a></div></details>'
 html+='</div></div></details>'
html+='</div></section><section class="wrap section team">'+heading('04 / LEADERSHIP','Real people.<br>Shared responsibility.','Meet the people guiding our direction, engineering, and delivery.')+'<div class="team-grid">'
for p in d['team']:
 html+=f'<article><div class="portrait"><img src="/assets/enitexa/{p["image"]}" alt="{p["name"]}" width="640" height="760" loading="lazy">'+link('https://www.linkedin.com/in/'+p['linkedin']+'/',f'<span class="sr-only">{p["name"]} on </span>LinkedIn ↗','portrait-link')+f'</div><h3>{p["name"]}</h3><p class="role">{p["role"]}</p><p>{p["bio"]}</p></article>'
html+='</div></section><section class="experience-band"><div class="wrap section">'+heading('05 / PROFESSIONAL EXPERIENCE','Practical experience<br>behind the work.','Sarang Rajan — Professional Background. Employment history is separate from Enitexa.ai’s company history and client work.')+'<div class="timeline">'
for date,role,company,body in d['experience']:
 html+=f'<details><summary><span class="timeline-date">{date}</span><span><strong>{role}</strong><small>{company}</small></span><span aria-hidden="true">＋</span></summary><p>{body}</p></details>'
html+='<p class="source-note">Dates and role names follow the published professional timeline; “Present” reflects that source. '+link('https://sarangrajan.in/','View professional portfolio ↗')+'</p></div></div></section>'
html+='<section class="wrap section" id="work">'+heading('06 / THE PORTFOLIO','Different challenges.<br>Thoughtful solutions.','Explore the published work, the technologies behind it, and the context for each contribution.')+'<div class="filters" role="group" aria-label="Filter projects">'+''.join(f'<button data-filter="{f}" aria-pressed="{str(i==0).lower()}">{f}</button>' for i,f in enumerate(['All','Mobile Apps','Web Platforms','Business Tools']))+'</div><p id="project-count" class="sr-only" aria-live="polite">7 projects</p><div class="portfolio-grid">'
for i,p in enumerate(d['projects']):
 html+=f'<article class="project" id="project-{i}" data-category="{p["filter"]}">{visual(p)}<div class="project-meta"><span>{p["category"]}</span><span>0{i+1}</span></div><h3>{p["name"]}</h3><p>{p["description"]}</p><details><summary>Project details <span aria-hidden="true">＋</span></summary><div><p>{p["scope"]}</p><p class="stack">{p["stack"]}</p><p class="source-note">{p["attribution"]}</p>'+ (link(p['url'],'Visit website ↗','text-link') if p.get('url') else '<p class="source-note">Verified product link unavailable.</p>')+'</div></details></article>'
html+='</div></section><section class="products-band"><div class="wrap section">'+heading('07 / PRODUCTS & DEMONSTRATIONS','Explore what’s taking shape.','A look inside our product concepts. These demonstrations use sample content and do not represent deployed customer systems.')+'<div class="product-demos">'
for name,status,desc,url,label in [('Enitexa.ai ERP','Prototype','Explore an ERP interface for operations, inventory, and team information. Sample data; end-to-end workflows are not verified.','erp/dashboard','Explore prototype'),('SaaS platform foundation','Demo','Browse interactive console variants for operations, reporting, and business workflows.','saas/demo','View Demo'),('AI assistant experience','In development','An assistant interface for product planning and technical ideas. Live AI service availability is not verified.','ai','Explore preview')]:
 html+=f'<article><span class="badge">{status}</span><h3>{name}</h3><p>{desc}</p>'+link('https://sarangrajan.in/enitexa.ai/'+url,label+' ↗','text-link')+'</article>'
html+='</div></div></section><section class="wrap section technology">'+heading('08 / TECHNOLOGY','The right tools.<br>For the right reasons.','Technology selection follows your product, team, and maintenance needs. Project records support the core stacks; additional languages and design tools are available for discussion.')+'<div class="tech-list">'
for name,items in [('Mobile','Flutter · Dart · React Native · Swift · Kotlin · Java'),('Web','React.js · Next.js · JavaScript · Tailwind CSS'),('Backend & integration','Node.js · Firebase · REST APIs · WebSockets'),('Data & infrastructure','AWS (published portfolio) · PostgreSQL (project-dependent)'),('Design','Figma · Adobe Illustrator · Photoshop')]:
 html+=f'<div><h3>{name}</h3><p>{items}</p></div>'
html+='</div></section><section class="process-band" id="process"><div class="wrap section">'+heading('09 / HOW WE WORK','Clear milestones.<br>Visible progress.<br>A practical handover.','Weekly reviews and milestone reporting keep priorities, decisions, and the next release visible.')+'<ol class="process-list">'
for title,desc in [('Discovery & scope','Understand the business need, users, constraints, and first-release priorities.'),('Product design & architecture','Define the experience, technical approach, and acceptance criteria.'),('Development & review','Build in milestones and review working features together.'),('QA & acceptance','Test agreed workflows and resolve issues against the acceptance criteria.'),('Launch & stabilization','Deploy the agreed release and address launch-stage issues.'),('Documentation & handover','Provide agreed repository access, deployment guidance, secure admin access transfer, walkthroughs, and maintenance notes.'),('Ongoing improvement','Plan enhancements and document ongoing support responsibilities in the service agreement.')]:
 html+=f'<li><h3>{title}</h3><p>{desc}</p></li>'
html+='</ol></div></section><section class="wrap section">'+heading('10 / WORKING TOGETHER','Start where you are.','Duration and deliverables follow the agreed scope. Choose the engagement that fits your next step.')+'<div class="engagement-list">'
for title,desc in [('Focused Project Sprint','A bounded feature, prototype, or specific business challenge.'),('End-to-End Product Development','A coordinated journey from product discovery to launch.'),('Dedicated Product Support','An ongoing backlog of maintenance and product improvements.'),('Architecture and Modernization Consulting','A practical review and plan for evolving existing systems.'),('Creative and Digital Support','Consistent design, content, and digital upkeep.')]:
 html+=f'<a href="#contact" data-engagement="{title}"><h3>{title}</h3><p>{desc}</p><span aria-hidden="true">↗</span></a>'
html+='</div></section><section class="wrap section usecases">'+heading('11 / BUSINESS USE CASES','Built around how you work.','Examples of needs we can support, rather than claims of delivered industry case studies.')+'<div class="usecase-grid">'
for title,desc in [('Startups & SaaS','MVP planning, user onboarding, and product foundations.'),('Retail & commerce','Catalogues, ordering, inventory, and billing.'),('Travel & hospitality','Tour discovery, reservation journeys, and guest communication.'),('Professional services','Lead management, company websites, and client portals.'),('Operational teams','Internal tools, approvals, and reporting.'),('Agencies & growing brands','Specialist engineering, design, video, and campaign support.')]:
 html+=f'<article><h3>{title}</h3><p>{desc}</p></article>'
html+='</div></section><section class="why-band"><div class="wrap section">'+heading('12 / WHY ENITEXA.AI','Connected thinking.<br>Accountable delivery.')+'<div class="why-grid">'
for title,desc in [('Technical + creative','Engineering and brand experience considered together, under one coordinated engagement.'),('Clarity throughout','Defined scope, regular reviews, and decisions tied to business priorities.'),('Ready for what follows','Maintainable implementation, practical documentation, and agreed handover responsibilities.')]:
 html+=f'<article><h3>{title}</h3><p>{desc}</p></article>'
html+='</div></div></section><section class="wrap section" id="faqs">'+heading('13 / A FEW ANSWERS','Good questions.<br>Clear answers.')+'<div class="faq-list">'
for q,a in d['faqs']:html+=f'<details><summary>{q}<span aria-hidden="true">＋</span></summary><p>{a}</p></details>'
html+='</div></section><section class="contact-band" id="contact"><div class="wrap section"><p class="eyebrow">14 / YOUR NEXT CHAPTER</p><div class="contact-grid"><div><h2>What are we<br>building <span>next?</span></h2><p>Tell us about the idea, the challenge, or the system that could work better. We’ll start from there.</p><div class="contact-links">'+link('mailto:'+d['contact']['email'],d['contact']['email']+' ↗')+link('tel:'+d['contact']['tel'],d['contact']['phone']+' ↗')+link('https://wa.me/919995254290','Start a conversation on WhatsApp ↗')+f'<p>{d["contact"]["location"]}</p></div></div>'
form=(ROOT/'data/enitexa/contact-form.html').read_text()
a=form.index('<div class="en-service-options">');b=form.index('</details>',a)
choices=''.join(f'<label><input type="checkbox" name="services" value="{e(title)}"><span>{e(title)}</span></label>' for group in d['services'] for title,_,_ in group[3])+'<label><input type="checkbox" name="services" value="Help me choose"><span>Help me choose</span></label>'
form=form[:a]+'<div class="en-service-options">'+choices+'</div>'+form[b:]
html+=form+'</div></div></section></main><footer class="wrap"><div class="footer-top"><a class="wordmark" href="#overview">✳ enitexa.ai</a><p>Ideas into everyday impact.</p>'+link('#overview','Back to top ↑')+'</div><div class="footer-bottom"><span>© 2026 Enitexa.ai</span>'+link('/','← Back to InfoparkDaily')+'<div>'+link('/privacy/','Privacy')+' · '+link('/terms/','Terms')+'</div></div></footer></body></html>'
(ROOT/'software-solutions/index.html').write_text(html)
print('Rendered software-solutions/index.html')
